In [ ]:
import numpy as np
import pandas as pd
data = {
    "Movie_ID": [
        "M001","M002","M003","M004","M005",
        "M006","M007","M008","M009","M010",
        "M011","M012","M013","M014","M015",
        "M016","M017","M018","M019","M020"
    ],

    "Movie_Name": [
        "Inception","Avatar","Titanic","The Dark Knight","Interstellar",
        "Frozen","Coco","Joker","Parasite","Avengers Endgame",
        "The Conjuring","Get Out","La La Land","Dune","Toy Story",
        "Black Panther","The Notebook","Shutter Island","Gladiator","The Godfather"
    ],

    "Genre": [
        "Sci-Fi","Action","Romance","Action","Sci-Fi",
        "Animation","Animation","Drama","Thriller","Action",
        "Horror","Horror","Musical","Sci-Fi","Animation",
        "Action","Romance","Thriller","Action","Crime"
    ],

    "Rating": [
        4.8,4.6,4.7,4.9,4.8,
        3.5,np.nan,4.4,4.6,np.nan,
        4.2,4.4,3.3,4.7,4.5,
        4.6,4.2,4.7,np.nan,4.1
    ],

    "Views": [
        15000,18000,20000,22000,17000,
        120000,110000,160000,0,25000,
        90000,85000,95000,145000,100000,
        175000,80000,125000,140000,210000
    ]
}

In [ ]:
df = pd.DataFrame(data)
print(df)

   Movie_ID        Movie_Name      Genre  Rating   Views
0      M001         Inception     Sci-Fi     4.8   15000
1      M002            Avatar     Action     4.6   18000
2      M003           Titanic    Romance     4.7   20000
3      M004   The Dark Knight     Action     4.9   22000
4      M005      Interstellar     Sci-Fi     4.8   17000
5      M006            Frozen  Animation     3.5  120000
6      M007              Coco  Animation     NaN  110000
7      M008             Joker      Drama     4.4  160000
8      M009          Parasite   Thriller     4.6       0
9      M010  Avengers Endgame     Action     NaN   25000
10     M011     The Conjuring     Horror     4.2   90000
11     M012           Get Out     Horror     4.4   85000
12     M013        La La Land    Musical     3.3   95000
13     M014              Dune     Sci-Fi     4.7  145000
14     M015         Toy Story  Animation     4.5  100000
15     M016     Black Panther     Action     4.6  175000
16     M017      The Notebook    Romance     4.2   80000
17     M018    Shutter Island   Thriller     4.7  125000
18     M019         Gladiator     Action     NaN  140000
19     M020     The Godfather      Crime     4.1  210000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Movie_ID    20 non-null     object
 1   Movie_Name  20 non-null     object
 2   Genre       20 non-null     object
 3   Rating      17 non-null     float64
 4   Views       20 non-null     int64
dtypes: float64(1), int64(1), object(3)
memory usage: 932.0+ bytes

In [ ]:
df.head()

  Movie_ID       Movie_Name    Genre  Rating  Views
0     M001        Inception   Sci-Fi     4.8  15000
1     M002           Avatar   Action     4.6  18000
2     M003          Titanic  Romance     4.7  20000
3     M004  The Dark Knight   Action     4.9  22000
4     M005     Interstellar   Sci-Fi     4.8  17000

In [ ]:
df.describe()

          Rating          Views
count  17.000000      20.000000
mean    4.411765   87600.000000
std     0.444244   61855.859613
min     3.300000       0.000000
25%     4.200000   21500.000000
50%     4.600000   92500.000000
75%     4.700000  128750.000000
max     4.900000  210000.000000

In [ ]:
df.isnull().sum()

Movie_ID      0
Movie_Name    0
Genre         0
Rating        3
Views         0
dtype: int64

In [ ]:
df["Rating"].fillna(df["Rating"].mean())

0     4.800000
1     4.600000
2     4.700000
3     4.900000
4     4.800000
5     3.500000
6     4.411765
7     4.400000
8     4.600000
9     4.411765
10    4.200000
11    4.400000
12    3.300000
13    4.700000
14    4.500000
15    4.600000
16    4.200000
17    4.700000
18    4.411765
19    4.100000
Name: Rating, dtype: float64

In [ ]:
print("Missing Values Before Cleaning")
df.isnull().sum()

Missing Values After Cleaning

Movie_ID      0
Movie_Name    0
Genre         0
Rating        0
Views         0
popularity    0
dtype: int64

In [ ]:
df["Rating"] = df["Rating"].fillna(df["Rating"].mean())

In [ ]:
print("Missing Values After Cleaning")
df.isnull().sum()

Missing Values After Cleaning

Movie_ID      0
Movie_Name    0
Genre         0
Rating        0
Views         0
popularity    0
dtype: int64

In [ ]:
df = df.drop_duplicates()
print(df)

   Movie_ID        Movie_Name      Genre    Rating   Views     popularity
0      M001         Inception     Sci-Fi  4.800000   15000   72000.000000
1      M002            Avatar     Action  4.600000   18000   82800.000000
2      M003           Titanic    Romance  4.700000   20000   94000.000000
3      M004   The Dark Knight     Action  4.900000   22000  107800.000000
4      M005      Interstellar     Sci-Fi  4.800000   17000   81600.000000
5      M006            Frozen  Animation  3.500000  120000  420000.000000
6      M007              Coco  Animation  4.411765  110000  485294.117647
7      M008             Joker      Drama  4.400000  160000  704000.000000
8      M009          Parasite   Thriller  4.600000       0       0.000000
9      M010  Avengers Endgame     Action  4.411765   25000  110294.117647
10     M011     The Conjuring     Horror  4.200000   90000  378000.000000
11     M012           Get Out     Horror  4.400000   85000  374000.000000
12     M013        La La Land    Musical  3.300000   95000  313500.000000
13     M014              Dune     Sci-Fi  4.700000  145000  681500.000000
14     M015         Toy Story  Animation  4.500000  100000  450000.000000
15     M016     Black Panther     Action  4.600000  175000  805000.000000
16     M017      The Notebook    Romance  4.200000   80000  336000.000000
17     M018    Shutter Island   Thriller  4.700000  125000  587500.000000
18     M019         Gladiator     Action  4.411765  140000  617647.058824
19     M020     The Godfather      Crime  4.100000  210000  861000.000000

In [ ]:
highrated = df[df["Rating"] > 4]

print(highrated)

   Movie_ID        Movie_Name      Genre    Rating   Views     popularity
0      M001         Inception     Sci-Fi  4.800000   15000   72000.000000
1      M002            Avatar     Action  4.600000   18000   82800.000000
2      M003           Titanic    Romance  4.700000   20000   94000.000000
3      M004   The Dark Knight     Action  4.900000   22000  107800.000000
4      M005      Interstellar     Sci-Fi  4.800000   17000   81600.000000
6      M007              Coco  Animation  4.411765  110000  485294.117647
7      M008             Joker      Drama  4.400000  160000  704000.000000
8      M009          Parasite   Thriller  4.600000       0       0.000000
9      M010  Avengers Endgame     Action  4.411765   25000  110294.117647
10     M011     The Conjuring     Horror  4.200000   90000  378000.000000
11     M012           Get Out     Horror  4.400000   85000  374000.000000
13     M014              Dune     Sci-Fi  4.700000  145000  681500.000000
14     M015         Toy Story  Animation  4.500000  100000  450000.000000
15     M016     Black Panther     Action  4.600000  175000  805000.000000
16     M017      The Notebook    Romance  4.200000   80000  336000.000000
17     M018    Shutter Island   Thriller  4.700000  125000  587500.000000
18     M019         Gladiator     Action  4.411765  140000  617647.058824
19     M020     The Godfather      Crime  4.100000  210000  861000.000000

In [ ]:
df["popularity"] = df["Views"] * df["Rating"]
print(df)

   Movie_ID        Movie_Name      Genre    Rating   Views     popularity
0      M001         Inception     Sci-Fi  4.800000   15000   72000.000000
1      M002            Avatar     Action  4.600000   18000   82800.000000
2      M003           Titanic    Romance  4.700000   20000   94000.000000
3      M004   The Dark Knight     Action  4.900000   22000  107800.000000
4      M005      Interstellar     Sci-Fi  4.800000   17000   81600.000000
5      M006            Frozen  Animation  3.500000  120000  420000.000000
6      M007              Coco  Animation  4.411765  110000  485294.117647
7      M008             Joker      Drama  4.400000  160000  704000.000000
8      M009          Parasite   Thriller  4.600000       0       0.000000
9      M010  Avengers Endgame     Action  4.411765   25000  110294.117647
10     M011     The Conjuring     Horror  4.200000   90000  378000.000000
11     M012           Get Out     Horror  4.400000   85000  374000.000000
12     M013        La La Land    Musical  3.300000   95000  313500.000000
13     M014              Dune     Sci-Fi  4.700000  145000  681500.000000
14     M015         Toy Story  Animation  4.500000  100000  450000.000000
15     M016     Black Panther     Action  4.600000  175000  805000.000000
16     M017      The Notebook    Romance  4.200000   80000  336000.000000
17     M018    Shutter Island   Thriller  4.700000  125000  587500.000000
18     M019         Gladiator     Action  4.411765  140000  617647.058824
19     M020     The Godfather      Crime  4.100000  210000  861000.000000

In [ ]:
sorted_movies = df.sort_values(by="popularity", ascending=False)
print(sorted_movies)

   Movie_ID        Movie_Name      Genre    Rating   Views     popularity
19     M020     The Godfather      Crime  4.100000  210000  861000.000000
15     M016     Black Panther     Action  4.600000  175000  805000.000000
7      M008             Joker      Drama  4.400000  160000  704000.000000
13     M014              Dune     Sci-Fi  4.700000  145000  681500.000000
18     M019         Gladiator     Action  4.411765  140000  617647.058824
17     M018    Shutter Island   Thriller  4.700000  125000  587500.000000
6      M007              Coco  Animation  4.411765  110000  485294.117647
14     M015         Toy Story  Animation  4.500000  100000  450000.000000
5      M006            Frozen  Animation  3.500000  120000  420000.000000
10     M011     The Conjuring     Horror  4.200000   90000  378000.000000
11     M012           Get Out     Horror  4.400000   85000  374000.000000
16     M017      The Notebook    Romance  4.200000   80000  336000.000000
12     M013        La La Land    Musical  3.300000   95000  313500.000000
9      M010  Avengers Endgame     Action  4.411765   25000  110294.117647
3      M004   The Dark Knight     Action  4.900000   22000  107800.000000
2      M003           Titanic    Romance  4.700000   20000   94000.000000
1      M002            Avatar     Action  4.600000   18000   82800.000000
4      M005      Interstellar     Sci-Fi  4.800000   17000   81600.000000
0      M001         Inception     Sci-Fi  4.800000   15000   72000.000000
8      M009          Parasite   Thriller  4.600000       0       0.000000

In [ ]:
avg = df.groupby("Genre")["Rating"].mean()

print(avg)

Genre
Action       4.584706
Animation    4.137255
Crime        4.100000
Drama        4.400000
Horror       4.300000
Musical      3.300000
Romance      4.450000
Sci-Fi       4.766667
Thriller     4.650000
Name: Rating, dtype: float64

In [ ]:
r = df["Rating"]

print(np.mean(r))

4.411764705882352

In [ ]:
np.median(r)

4.455882352941177

In [ ]:
df["Rating"].median()

4.455882352941177

In [ ]:
df["Rating"].max()

4.9

In [ ]:
df["Rating"].min()

3.3

In [ ]:
df["Rating"].std()

0.40766646963467124

In [ ]:
most = df.loc[df["popularity"].idxmax()]

print(most)

Movie_ID               M020
Movie_Name    The Godfather
Genre                 Crime
Rating                  4.1
Views                210000
popularity         861000.0
Name: 19, dtype: object

In [ ]:
print("Popularity score =")
print(df["popularity"])

Popularity score =
0      72000.000000
1      82800.000000
2      94000.000000
3     107800.000000
4      81600.000000
5     420000.000000
6     485294.117647
7     704000.000000
8          0.000000
9     110294.117647
10    378000.000000
11    374000.000000
12    313500.000000
13    681500.000000
14    450000.000000
15    805000.000000
16    336000.000000
17    587500.000000
18    617647.058824
19    861000.000000
Name: popularity, dtype: float64

In [ ]:
print("\nInsights")
print("Total num of movies = ", len(df))
print("High rated movies = ", highrated)
print("Popularity score = ", df["Views"] * df["Rating"])
print("sorted ratings= ", sorted)
print("Average rating = ", avg)
print("Most popular movie = ", most)

Insights
Total num of movies =  20
High rated movies =     Movie_ID        Movie_Name      Genre    Rating   Views     popularity
0      M001         Inception     Sci-Fi  4.800000   15000   72000.000000
1      M002            Avatar     Action  4.600000   18000   82800.000000
2      M003           Titanic    Romance  4.700000   20000   94000.000000
3      M004   The Dark Knight     Action  4.900000   22000  107800.000000
4      M005      Interstellar     Sci-Fi  4.800000   17000   81600.000000
6      M007              Coco  Animation  4.411765  110000  485294.117647
7      M008             Joker      Drama  4.400000  160000  704000.000000
8      M009          Parasite   Thriller  4.600000       0       0.000000
9      M010  Avengers Endgame     Action  4.411765   25000  110294.117647
10     M011     The Conjuring     Horror  4.200000   90000  378000.000000
11     M012           Get Out     Horror  4.400000   85000  374000.000000
13     M014              Dune     Sci-Fi  4.700000  145000  681500.000000
14     M015         Toy Story  Animation  4.500000  100000  450000.000000
15     M016     Black Panther     Action  4.600000  175000  805000.000000
16     M017      The Notebook    Romance  4.200000   80000  336000.000000
17     M018    Shutter Island   Thriller  4.700000  125000  587500.000000
18     M019         Gladiator     Action  4.411765  140000  617647.058824
19     M020     The Godfather      Crime  4.100000  210000  861000.000000
Popularity score =  0      72000.000000
1      82800.000000
2      94000.000000
3     107800.000000
4      81600.000000
5     420000.000000
6     485294.117647
7     704000.000000
8          0.000000
9     110294.117647
10    378000.000000
11    374000.000000
12    313500.000000
13    681500.000000
14    450000.000000
15    805000.000000
16    336000.000000
17    587500.000000
18    617647.058824
19    861000.000000
dtype: float64
sorted ratings=  <built-in function sorted>
Average rating =  Genre
Action       4.584706
Animation    4.137255
Crime        4.100000
Drama        4.400000
Horror       4.300000
Musical      3.300000
Romance      4.450000
Sci-Fi       4.766667
Thriller     4.650000
Name: Rating, dtype: float64
Most popular movie =  Movie_ID               M020
Movie_Name    The Godfather
Genre                 Crime
Rating                  4.1
Views                210000
popularity         861000.0
Name: 19, dtype: object