#  TTT AIML & Python – Day 5

##  Data Cleaning & Preprocessing

---

###  Objective:
Learn how to clean, preprocess, and prepare data before applying Machine Learning models.

---

###  Why this matters?
Garbage Data  → Garbage Output
Clean Data  → Better Models

In [ ]:
import pandas as pd
import numpy as np

##  What is Data Cleaning?

Data Cleaning is the process of:
- Fixing incorrect data
- Handling missing values
- Removing duplicates
- Standardizing formats

---

##  Why is Data Preprocessing Important?

Machine Learning models:
- Cannot handle missing or messy data properly
- Require numerical and consistent input

---

##  Example of Messy Data:

| Name | Age | City     |
|------|-----|----------|
| Ram  | 25  | Mumbai   |
| Shyam| NaN | mumbai   |
| Ram  | 25  | Mumbai   |

Problems:
- Missing values
- Inconsistent text
- Duplicate rows

In [ ]:
import pandas as pd
import numpy as np

employee_data = {
    "Employee_ID": [101,102,103,104,105,106,107,108,109,109,110,111,112,113,114],

    "Name": [
        "Rahul",
        "Priya",
        "Amit",
        None,
        "Sneha",
        "Rahul",
        "Kiran",
        "Anjali",
        "Vijay",
        "Vijay",
        "Deepa",
        "Arun",
        None,
        "Meena",
        "Rohit"
    ],

    "Age": [
        25,
        np.nan,
        28,
        35,
        29,
        25,
        150,
        31,
        27,
        27,
        np.nan,
        26,
        30,
        -5,
        32
    ],

    "Salary": [
        35000,
        42000,
        np.nan,
        50000,
        47000,
        35000,
        999999,
        45000,
        39000,
        39000,
        41000,
        np.nan,
        48000,
        46000,
        44000
    ],

    "Department": [
        "HR",
        "IT",
        "Finance",
        "HR",
        "IT",
        "HR",
        "Finance",
        "Marketing",
        None,
        None,
        "IT",
        "marketing",
        "Finance",
        "HR",
        "IT"
    ],

    "City": [
        "Hyderabad",
        "hyderabad",
        "Mumbai",
        "Delhi",
        " Delhi",
        "Hyderabad",
        "MUMBAI",
        "Chennai",
        "Pune",
        "Pune",
        "Delhi",
        "CHENNAI",
        "Mumbai",
        "Hyderabad ",
        None
    ],

    "Joining_Date": [
        "2023-01-10",
        "2022/05/14",
        "15-08-2021",
        "2021-12-05",
        "Invalid Date",
        "2023-01-10",
        "2020-07-19",
        None,
        "2024-03-15",
        "2024-03-15",
        "2022-09-01",
        "2023-11-10",
        "2021/02/25",
        "2020-10-30",
        "2024-01-05"
    ],

    "Performance": [
        "Excellent",
        "Good",
        "Average",
        "Excellent",
        "Poor",
        "Excellent",
        "Good",
        "Average",
        "excellent",
        "excellent",
        None,
        "GOOD",
        "Poor",
        "Average",
        "Good"
    ]
}

df = pd.DataFrame(employee_data)

🛠️ Tasks to Perform

The following tasks should be completed in sequence:

 Part 1:Dataset Inspection
1. Understand the structure of the data.
2. Identify missing values.
3. Handle missing values using appropriate techniques.
4. Detect duplicate records.
5. Remove duplicate records.
6. Standardize inconsistent text values.
7. Convert columns into appropriate data types.
8. Convert the date column into datetime format.
9. Create useful date-related features.
10. Encode categorical variables.
11. Detect and handle outliers.
12. Validate the cleaned dataset.
13. Save the cleaned dataset as CSV and Excel files.

### Part 1: Dataset Inspection
- Load the dataset.
- Display the dataset.
- Inspect the first and last few rows.
- Check the dataset shape.
- View column names.
- Examine data types.
- Generate summary statistics.

In [ ]:
#1.Display Dataset

df

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,25.0,35000.0,HR,Hyderabad,2023-01-10,Excellent
1,102,Priya,NaN,42000.0,IT,hyderabad,2022/05/14,Good
2,103,Amit,28.0,NaN,Finance,Mumbai,15-08-2021,Average
3,104,None,35.0,50000.0,HR,Delhi,2021-12-05,Excellent
4,105,Sneha,29.0,47000.0,IT,Delhi,Invalid Date,Poor
5,106,Rahul,25.0,35000.0,HR,Hyderabad,2023-01-10,Excellent
6,107,Kiran,150.0,999999.0,Finance,MUMBAI,2020-07-19,Good
7,108,Anjali,31.0,45000.0,Marketing,Chennai,None,Average
8,109,Vijay,27.0,39000.0,None,Pune,2024-03-15,excellent
9,109,Vijay,27.0,39000.0,None,Pune,2024-03-15,excellent
10,110,Deepa,NaN,41000.0,IT,Delhi,2022-09-01,None
11,111,Arun,26.0,NaN,marketing,CHENNAI,2023-11-10,GOOD
12,112,None,30.0,48000.0,Finance,Mumbai,2021/02/25,Poor
13,113,Meena,-5.0,46000.0,HR,Hyderabad,2020-10-30,Average
14,114,Rohit,32.0,44000.0,IT,None,2024-01-05,Good

In [ ]:
#2.First Five Rows

df.head()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,25.0,35000.0,HR,Hyderabad,2023-01-10,Excellent
1,102,Priya,NaN,42000.0,IT,hyderabad,2022/05/14,Good
2,103,Amit,28.0,NaN,Finance,Mumbai,15-08-2021,Average
3,104,None,35.0,50000.0,HR,Delhi,2021-12-05,Excellent
4,105,Sneha,29.0,47000.0,IT,Delhi,Invalid Date,Poor

In [ ]:
#3.Last Five Rows

df.tail()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
10,110,Deepa,NaN,41000.0,IT,Delhi,2022-09-01,None
11,111,Arun,26.0,NaN,marketing,CHENNAI,2023-11-10,GOOD
12,112,None,30.0,48000.0,Finance,Mumbai,2021/02/25,Poor
13,113,Meena,-5.0,46000.0,HR,Hyderabad,2020-10-30,Average
14,114,Rohit,32.0,44000.0,IT,None,2024-01-05,Good

In [ ]:
#4.Dataset Shape

df.shape

(15, 8)

In [ ]:
#5.Column Names

df.columns

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City',
       'Joining_Date', 'Performance'],
      dtype='object')

In [ ]:
#6.Data Types

df.dtypes

Employee_ID       int64
Name             object
Age             float64
Salary          float64
Department       object
City             object
Joining_Date     object
Performance      object
dtype: object

In [ ]:
#7.Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   15 non-null     int64
 1   Name          13 non-null     object
 2   Age           13 non-null     float64
 3   Salary        13 non-null     float64
 4   Department    13 non-null     object
 5   City          14 non-null     object
 6   Joining_Date  14 non-null     object
 7   Performance   14 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.1+ KB

In [ ]:
#8.Summary Statistics

df.describe()

       Employee_ID         Age         Salary
count    15.000000   13.000000      13.000000
mean    107.600000   35.384615  116230.692308
std       4.049691   35.785329  265581.208571
min     101.000000   -5.000000   35000.000000
25%     104.500000   26.000000   39000.000000
50%     108.000000   28.000000   44000.000000
75%     110.500000   31.000000   47000.000000
max     114.000000  150.000000  999999.000000

In [ ]:
#9.Summary Statistics (Including Text Columns)

df.describe(include="all")

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
count,15.000000,13,13.000000,13.000000,13,14,14,14
unique,NaN,11,NaN,NaN,5,10,12,6
top,NaN,Rahul,NaN,NaN,HR,Hyderabad,2023-01-10,Excellent
freq,NaN,2,NaN,NaN,4,2,2,3
mean,107.600000,NaN,35.384615,116230.692308,NaN,NaN,NaN,NaN
std,4.049691,NaN,35.785329,265581.208571,NaN,NaN,NaN,NaN
min,101.000000,NaN,-5.000000,35000.000000,NaN,NaN,NaN,NaN
25%,104.500000,NaN,26.000000,39000.000000,NaN,NaN,NaN,NaN
50%,108.000000,NaN,28.000000,44000.000000,NaN,NaN,NaN,NaN
75%,110.500000,NaN,31.000000,47000.000000,NaN,NaN,NaN,NaN
max,114.000000,NaN,150.000000,999999.000000,NaN,NaN,NaN,NaN

In [ ]:
#10.Missing Values

print("Missing Values Before Handling:\n")
df.isnull().sum()

Missing Values Before Handling:

Employee_ID     0
Name            2
Age             2
Salary          2
Department      2
City            1
Joining_Date    1
Performance     1
dtype: int64

##  Missing Values

Missing values are represented as:
- NaN (Not a Number)
- None

---

##  Steps:
1. Identify missing values
2. Count them
3. Decide:
   - Drop
   - Fill

##  Filling Missing Values

### Numerical Columns:
- Mean
- Median

### Categorical Columns:
- Mode

---

##  When to Use:
- Mean → Normal data
- Median → Skewed data
- Mode → Categories


###Part 2: Handling Missing Values
- Identify missing values Name,Age,Salary,Department,City,Joining_Date,Performance.
- Handle numerical missing values using appropriate techniques.
- Handle categorical missing values using appropriate techniques.
- Verify that all missing values have been handled successfully.

In [ ]:
#Step 1: Handle Numerical Columns

# Fill missing Age using Median
# (Median is preferred because the dataset contains outliers like 150 and -5)

df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Salary using Median
# (Median is more robust because Salary contains an extreme outlier: 999999)

df["Salary"] = df["Salary"].fillna(df["Salary"].median())

In [ ]:
#Step 2: Handle Categorical Columns

## Fill missing Name using Mode
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])

## Fill missing Department using Mode
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

## Fill missing City using Mode
df['City'] = df['City'].fillna(df['City'].mode()[0])

## Fill missing Performance using Mode
df['Performance'] = df['Performance'].fillna(df['Performance'].mode()[0])

In [ ]:
#Step 3: Handle Date Column

# Fill missing Joining_Date using Mode
# (Another common option is forward fill, but mode keeps this exercise simple.)

df["Joining_Date"] = df["Joining_Date"].fillna(df["Joining_Date"].mode()[0])

In [ ]:
print("Missing Values After Handling:\n")
print(df.isnull().sum())

Missing Values After Handling:

Employee_ID     0
Name            0
Age             0
Salary          0
Department      0
City            0
Joining_Date    0
Performance     0
dtype: int64

###Part 3: Handling Duplicate Records
- Detect duplicate records.
- Display duplicate rows.
- Remove duplicate records.
- Verify that duplicate records have been removed.

In [ ]:
#Display All Duplicate Entries

print("Duplicate Records Before Handling:\n")
df.duplicated().sum()

Duplicate Records Before Handling:

np.int64(1)

In [ ]:
#Remove Duplicate Records

df2 = df.drop_duplicates()

In [ ]:
#Verify Duplicate Removal

print("Duplicate Records After Handling:\n")
df2.duplicated().sum()

Duplicate Records After Handling:

np.int64(0)

In [ ]:
#Display Updated Dataset

df2

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,25.0,35000.0,HR,Hyderabad,2023-01-10,Excellent
1,102,Priya,28.0,42000.0,IT,hyderabad,2022/05/14,Good
2,103,Amit,28.0,44000.0,Finance,Mumbai,15-08-2021,Average
3,104,Rahul,35.0,50000.0,HR,Delhi,2021-12-05,Excellent
4,105,Sneha,29.0,47000.0,IT,Delhi,Invalid Date,Poor
5,106,Rahul,25.0,35000.0,HR,Hyderabad,2023-01-10,Excellent
6,107,Kiran,150.0,999999.0,Finance,MUMBAI,2020-07-19,Good
7,108,Anjali,31.0,45000.0,Marketing,Chennai,2023-01-10,Average
8,109,Vijay,27.0,39000.0,HR,Pune,2024-03-15,excellent
10,110,Deepa,28.0,41000.0,IT,Delhi,2022-09-01,Average
11,111,Arun,26.0,44000.0,marketing,CHENNAI,2023-11-10,GOOD
12,112,Rahul,30.0,48000.0,Finance,Mumbai,2021/02/25,Poor
13,113,Meena,-5.0,46000.0,HR,Hyderabad,2020-10-30,Average
14,114,Rohit,32.0,44000.0,IT,Delhi,2024-01-05,Good

In [ ]:
#Check Dataset Shape

df2.shape

(14, 8)

###Part 4: Text Cleaning & Standardization
- Identify inconsistent text values.
- Remove extra spaces.
- Convert text into a consistent format.
- Verify the cleaned text values.

In [ ]:
#Step 1: Display Unique Values

# ==========================================
# Display Unique Values
# ==========================================

print("Unique City Values:\n")
print(df2["City"].unique())

print("\nUnique Department Values:\n")
print(df2["Department"].unique())

print("\nUnique Performance Values:\n")
print(df2["Performance"].unique())

Unique City Values:

['Hyderabad' 'hyderabad' 'Mumbai' 'Delhi' ' Delhi' 'MUMBAI' 'Chennai'
 'Pune' 'CHENNAI' 'Hyderabad ']

Unique Department Values:

['HR' 'IT' 'Finance' 'Marketing' 'marketing']

Unique Performance Values:

['Excellent' 'Good' 'Average' 'Poor' 'excellent' 'GOOD']

In [ ]:
#Step 2: Remove Extra Spaces

# ==========================================
# Remove Leading and Trailing Spaces
# ==========================================

text_columns = ["City", "Department", "Performance"]

for column in text_columns:
    df2[column] = df2[column].str.strip()

/tmp/ipykernel_1010/1712610883.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column] = df2[column].str.strip()

In [ ]:
#Step 3: Convert Text to Uppercase

# ==========================================
# Convert Text to Uppercase
# ==========================================

for column in text_columns:
    df2[column] = df2[column].str.upper()

/tmp/ipykernel_1010/682168036.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column] = df2[column].str.upper()

In [ ]:
#Step 4: Verify Cleaned Values

# ==========================================
# Verify Updated Values
# ==========================================

print("Updated City Values:\n")
print(df2["City"].unique())

print("\nUpdated Department Values:\n")
print(df2["Department"].unique())

print("\nUpdated Performance Values:\n")
print(df2["Performance"].unique())

Updated City Values:

['HYDERABAD' 'MUMBAI' 'DELHI' 'CHENNAI' 'PUNE']

Updated Department Values:

['HR' 'IT' 'FINANCE' 'MARKETING']

Updated Performance Values:

['EXCELLENT' 'GOOD' 'AVERAGE' 'POOR']

In [ ]:
df2

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,25.0,35000.0,HR,HYDERABAD,2023-01-10,EXCELLENT
1,102,Priya,28.0,42000.0,IT,HYDERABAD,2022/05/14,GOOD
2,103,Amit,28.0,44000.0,FINANCE,MUMBAI,15-08-2021,AVERAGE
3,104,Rahul,35.0,50000.0,HR,DELHI,2021-12-05,EXCELLENT
4,105,Sneha,29.0,47000.0,IT,DELHI,Invalid Date,POOR
5,106,Rahul,25.0,35000.0,HR,HYDERABAD,2023-01-10,EXCELLENT
6,107,Kiran,150.0,999999.0,FINANCE,MUMBAI,2020-07-19,GOOD
7,108,Anjali,31.0,45000.0,MARKETING,CHENNAI,2023-01-10,AVERAGE
8,109,Vijay,27.0,39000.0,HR,PUNE,2024-03-15,EXCELLENT
10,110,Deepa,28.0,41000.0,IT,DELHI,2022-09-01,AVERAGE
11,111,Arun,26.0,44000.0,MARKETING,CHENNAI,2023-11-10,GOOD
12,112,Rahul,30.0,48000.0,FINANCE,MUMBAI,2021/02/25,POOR
13,113,Meena,-5.0,46000.0,HR,HYDERABAD,2020-10-30,AVERAGE
14,114,Rohit,32.0,44000.0,IT,DELHI,2024-01-05,GOOD

In [ ]:
#Step 5: Count Unique Values

# ==========================================
# Count Unique Categories
# ==========================================

print(df2["City"].nunique())

print(df2["Department"].nunique())

print(df2["Performance"].nunique())

5
4
4

In [ ]:
#Step 6: Display Cleaned Dataset

# ==========================================
# Display Updated Dataset
# ==========================================

df2.head()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,25.0,35000.0,HR,HYDERABAD,2023-01-10,EXCELLENT
1,102,Priya,28.0,42000.0,IT,HYDERABAD,2022/05/14,GOOD
2,103,Amit,28.0,44000.0,FINANCE,MUMBAI,15-08-2021,AVERAGE
3,104,Rahul,35.0,50000.0,HR,DELHI,2021-12-05,EXCELLENT
4,105,Sneha,29.0,47000.0,IT,DELHI,Invalid Date,POOR

###Part 5: Data Type Conversion
- Check existing data types.
- Convert numerical columns into appropriate data types.
- Convert the date column into datetime format.
- Verify the updated data types.

In [ ]:
# ==========================================
# Check Current Data Types
# ==========================================

print("Current Data Types:\n")

print(df2.dtypes)

Current Data Types:

Employee_ID       int64
Name             object
Age             float64
Salary          float64
Department       object
City             object
Joining_Date     object
Performance      object
dtype: object

In [ ]:
# ==========================================
# Display Dataset Information
# ==========================================

df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 14
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   14 non-null     int64
 1   Name          14 non-null     object
 2   Age           14 non-null     float64
 3   Salary        14 non-null     float64
 4   Department    14 non-null     object
 5   City          14 non-null     object
 6   Joining_Date  14 non-null     object
 7   Performance   14 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1008.0+ bytes

In [ ]:
# ==========================================
# Remove Extra Spaces
# ==========================================

df2["Joining_Date"] = df2["Joining_Date"].astype(str).str.strip()

/tmp/ipykernel_1010/1890608634.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Joining_Date"] = df2["Joining_Date"].astype(str).str.strip()

In [ ]:
# ==========================================
# Convert Joining_Date to Datetime
# ==========================================

df2["Joining_Date"] = pd.to_datetime(
    df2["Joining_Date"],
    errors="coerce"
)

/tmp/ipykernel_1010/2983918308.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Joining_Date"] = pd.to_datetime(

In [ ]:
# ==========================================
# Verify Data Types
# ==========================================

print(df2.dtypes)

Employee_ID              int64
Name                    object
Age                    float64
Salary                 float64
Department              object
City                    object
Joining_Date    datetime64[ns]
Performance             object
dtype: object

In [ ]:
# ==========================================
# Find Invalid Dates
# ==========================================

invalid_dates = df2[df2["Joining_Date"].isnull()]

invalid_dates

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
1,102,Priya,28.0,42000.0,IT,HYDERABAD,NaT,GOOD
2,103,Amit,28.0,44000.0,FINANCE,MUMBAI,NaT,AVERAGE
4,105,Sneha,29.0,47000.0,IT,DELHI,NaT,POOR
12,112,Rahul,30.0,48000.0,FINANCE,MUMBAI,NaT,POOR

In [ ]:
# ==========================================
# Convert Age to Integer
# ==========================================

df2["Age"] = df2["Age"].astype(int)

/tmp/ipykernel_1010/2328709954.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Age"] = df2["Age"].astype(int)

In [ ]:
df2

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,25,35000.0,HR,HYDERABAD,2023-01-10,EXCELLENT
1,102,Priya,28,42000.0,IT,HYDERABAD,NaT,GOOD
2,103,Amit,28,44000.0,FINANCE,MUMBAI,NaT,AVERAGE
3,104,Rahul,35,50000.0,HR,DELHI,2021-12-05,EXCELLENT
4,105,Sneha,29,47000.0,IT,DELHI,NaT,POOR
5,106,Rahul,25,35000.0,HR,HYDERABAD,2023-01-10,EXCELLENT
6,107,Kiran,150,999999.0,FINANCE,MUMBAI,2020-07-19,GOOD
7,108,Anjali,31,45000.0,MARKETING,CHENNAI,2023-01-10,AVERAGE
8,109,Vijay,27,39000.0,HR,PUNE,2024-03-15,EXCELLENT
10,110,Deepa,28,41000.0,IT,DELHI,2022-09-01,AVERAGE
11,111,Arun,26,44000.0,MARKETING,CHENNAI,2023-11-10,GOOD
12,112,Rahul,30,48000.0,FINANCE,MUMBAI,NaT,POOR
13,113,Meena,-5,46000.0,HR,HYDERABAD,2020-10-30,AVERAGE
14,114,Rohit,32,44000.0,IT,DELHI,2024-01-05,GOOD

In [ ]:
# ==========================================
# Convert Salary to Integer
# ==========================================

df2["Salary"] = df2["Salary"].astype(int)

/tmp/ipykernel_1010/2017292676.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Salary"] = df2["Salary"].astype(int)

In [ ]:
# ==========================================
# Convert Object Columns to Category
# ==========================================

categorical_columns = [
    "Department",
    "City",
    "Performance"
]

for column in categorical_columns:
    df2[column] = df2[column].astype("category")

/tmp/ipykernel_1010/310744611.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column] = df2[column].astype("category")
/tmp/ipykernel_1010/310744611.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column] = df2[column].astype("category")
/tmp/ipykernel_1010/310744611.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column] = df2[column].astype("category")

In [ ]:
# ==========================================
# Final Data Types
# ==========================================

df2.dtypes

Employee_ID              int64
Name                    object
Age                      int64
Salary                   int64
Department            category
City                  category
Joining_Date    datetime64[ns]
Performance           category
dtype: object

In [ ]:
# ==========================================
# Display Updated Dataset
# ==========================================

df2.head()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,25,35000,HR,HYDERABAD,2023-01-10,EXCELLENT
1,102,Priya,28,42000,IT,HYDERABAD,NaT,GOOD
2,103,Amit,28,44000,FINANCE,MUMBAI,NaT,AVERAGE
3,104,Rahul,35,50000,HR,DELHI,2021-12-05,EXCELLENT
4,105,Sneha,29,47000,IT,DELHI,NaT,POOR

##  Selecting Multiple Columns

To work on multiple columns together:

###  Syntax:
df[["col1", "col2"]]

---

##  Why use this?
- Apply same operation on multiple columns
- Clean multiple columns at once
- Save time and avoid repetition

In [ ]:
# ==========================================
# Selecting Multiple Columns
# ==========================================

# Select Age and Salary columns

selected_columns = df[["Age", "Salary"]]

print(selected_columns)

      Age    Salary
0    25.0   35000.0
1    28.0   42000.0
2    28.0   44000.0
3    35.0   50000.0
4    29.0   47000.0
5    25.0   35000.0
6   150.0  999999.0
7    31.0   45000.0
8    27.0   39000.0
9    27.0   39000.0
10   28.0   41000.0
11   26.0   44000.0
12   30.0   48000.0
13   -5.0   46000.0
14   32.0   44000.0

In [ ]:
# ==========================================
# Convert Multiple Columns to Integer
# ==========================================

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

print(df.dtypes)

Employee_ID      int64
Name            object
Age              int64
Salary           int64
Department      object
City            object
Joining_Date    object
Performance     object
dtype: object

In [ ]:
# ==========================================
# Increase Age and Salary by 10%
# ==========================================

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(
    lambda column: column * 1.10
)

print(df[["Age", "Salary"]].head())

    Age   Salary
0  27.5  38500.0
1  30.8  46200.0
2  30.8  48400.0
3  38.5  55000.0
4  31.9  51700.0

In [ ]:
# Convert back to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.head()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,27,38500,HR,Hyderabad,2023-01-10,Excellent
1,102,Priya,30,46200,IT,hyderabad,2022/05/14,Good
2,103,Amit,30,48400,Finance,Mumbai,15-08-2021,Average
3,104,Rahul,38,55000,HR,Delhi,2021-12-05,Excellent
4,105,Sneha,31,51700,IT,Delhi,Invalid Date,Poor

In [ ]:
#replace()

# ==========================================
# Replace a Single Value
# ==========================================

df2["City"] = df2["City"].replace("HYDERABAD", "HYD")

print(df2["City"].unique())

['HYD', 'MUMBAI', 'DELHI', 'CHENNAI', 'PUNE']
Categories (5, object): ['CHENNAI', 'DELHI', 'HYD', 'MUMBAI', 'PUNE']

/tmp/ipykernel_1010/3299168254.py:7: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df2["City"] = df2["City"].replace("HYDERABAD", "HYD")
/tmp/ipykernel_1010/3299168254.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["City"] = df2["City"].replace("HYDERABAD", "HYD")

In [ ]:
# ==========================================
# Replace Multiple Values
# ==========================================

df["Department"] = df["Department"].replace({
    "HR": "Human Resources",
    "IT": "Information Technology",
    "FINANCE": "Finance",
    "MARKETING": "Marketing"
})

print(df["Department"].unique())

['Human Resources' 'Information Technology' 'Finance' 'Marketing'
 'marketing']

In [ ]:
# ==========================================
# Replace Values in Multiple Columns
# ==========================================

df = df.replace({
    "GOOD": "Good",
    "AVERAGE": "Average",
    "EXCELLENT": "Excellent",
    "POOR": "Poor"
})

df.head()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,27,38500,Human Resources,Hyderabad,2023-01-10,Excellent
1,102,Priya,30,46200,Information Technology,hyderabad,2022/05/14,Good
2,103,Amit,30,48400,Finance,Mumbai,15-08-2021,Average
3,104,Rahul,38,55000,Human Resources,Delhi,2021-12-05,Excellent
4,105,Sneha,31,51700,Information Technology,Delhi,Invalid Date,Poor

###Part 6: Feature Engineering
- Extract Year from the date column.
- Extract Month from the date column.
- Extract Day from the date column.
- Extract Weekday.
- Extract Quarter.
- Extract Month Name.
- Create a Weekend indicator.
- Calculate Years of Service.

In [ ]:
# ==========================================
# Display Dataset
# ==========================================

df2.head()

   Employee_ID   Name  Age  Salary Department    City Joining_Date Performance
0          101  Rahul   25   35000         HR     HYD   2023-01-10   EXCELLENT
1          102  Priya   28   42000         IT     HYD          NaT        GOOD
2          103   Amit   28   44000    FINANCE  MUMBAI          NaT     AVERAGE
3          104  Rahul   35   50000         HR   DELHI   2021-12-05   EXCELLENT
4          105  Sneha   29   47000         IT   DELHI          NaT        POOR

In [ ]:
# ==========================================
# Extract Joining Year
# ==========================================

df2["Joining_Year"] = df2["Joining_Date"].dt.year

/tmp/ipykernel_1010/817691289.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Joining_Year"] = df2["Joining_Date"].dt.year

In [ ]:
# ==========================================
# Extract Joining Month
# ==========================================

df2["Joining_Month"] = df2["Joining_Date"].dt.month

/tmp/ipykernel_1010/949945065.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Joining_Month"] = df2["Joining_Date"].dt.month

In [ ]:
# ==========================================
# Extract Joining Day
# ==========================================

df2["Joining_Day"] = df2["Joining_Date"].dt.day

/tmp/ipykernel_1010/1517087476.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Joining_Day"] = df2["Joining_Date"].dt.day

In [ ]:
# ==========================================
# Extract Weekday
# ==========================================

df2["Weekday"] = df2["Joining_Date"].dt.day_name()

/tmp/ipykernel_1010/1885748686.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Weekday"] = df2["Joining_Date"].dt.day_name()

In [ ]:
# ==========================================
# Extract Quarter
# ==========================================

df2["Quarter"] = df2["Joining_Date"].dt.quarter

/tmp/ipykernel_1010/580673928.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Quarter"] = df2["Joining_Date"].dt.quarter

In [ ]:
# ==========================================
# Extract Month Name
# ==========================================

df2["Month_Name"] = df2["Joining_Date"].dt.month_name()

/tmp/ipykernel_1010/1459895735.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Month_Name"] = df2["Joining_Date"].dt.month_name()

In [ ]:
# ==========================================
# Weekend or Weekday
# ==========================================

df2["Is_Weekend"] = df2["Joining_Date"].dt.dayofweek >= 5

/tmp/ipykernel_1010/1155403612.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Is_Weekend"] = df2["Joining_Date"].dt.dayofweek >= 5

In [ ]:
# ==========================================
# Calculate Years of Service
# ==========================================

current_year = pd.Timestamp.now().year

df2["Years_of_Service"] = current_year - df2["Joining_Year"]

/tmp/ipykernel_1010/4268607009.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Years_of_Service"] = current_year - df2["Joining_Year"]

In [ ]:
# ==========================================
# Display Feature Engineered Dataset
# ==========================================

df2.head()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance,Joining_Year,Joining_Month,Joining_Day,Weekday,Quarter,Month_Name,Is_Weekend,Years_of_Service
0,101,Rahul,25,35000,HR,HYD,2023-01-10,EXCELLENT,2023.0,1.0,10.0,Tuesday,1.0,January,False,3.0
1,102,Priya,28,42000,IT,HYD,NaT,GOOD,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
2,103,Amit,28,44000,FINANCE,MUMBAI,NaT,AVERAGE,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
3,104,Rahul,35,50000,HR,DELHI,2021-12-05,EXCELLENT,2021.0,12.0,5.0,Sunday,4.0,December,True,5.0
4,105,Sneha,29,47000,IT,DELHI,NaT,POOR,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [ ]:
df2[df2["Joining_Date"].isnull()]

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance,Joining_Year,Joining_Month,Joining_Day,Weekday,Quarter,Month_Name,Is_Weekend,Years_of_Service
1,102,Priya,28,42000,IT,HYD,NaT,GOOD,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
2,103,Amit,28,44000,FINANCE,MUMBAI,NaT,AVERAGE,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
4,105,Sneha,29,47000,IT,DELHI,NaT,POOR,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
12,112,Rahul,30,48000,FINANCE,MUMBAI,NaT,POOR,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [ ]:
df2["Joining_Date"] = df2["Joining_Date"].fillna(
    df2["Joining_Date"].mode()[0]
)

/tmp/ipykernel_1010/2390935527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Joining_Date"] = df2["Joining_Date"].fillna(

In [ ]:
df2

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance,Joining_Year,Joining_Month,Joining_Day,Weekday,Quarter,Month_Name,Is_Weekend,Years_of_Service
0,101,Rahul,25,35000,HR,HYD,2023-01-10,EXCELLENT,2023.0,1.0,10.0,Tuesday,1.0,January,False,3.0
1,102,Priya,28,42000,IT,HYD,2023-01-10,GOOD,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
2,103,Amit,28,44000,FINANCE,MUMBAI,2023-01-10,AVERAGE,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
3,104,Rahul,35,50000,HR,DELHI,2021-12-05,EXCELLENT,2021.0,12.0,5.0,Sunday,4.0,December,True,5.0
4,105,Sneha,29,47000,IT,DELHI,2023-01-10,POOR,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
5,106,Rahul,25,35000,HR,HYD,2023-01-10,EXCELLENT,2023.0,1.0,10.0,Tuesday,1.0,January,False,3.0
6,107,Kiran,150,999999,FINANCE,MUMBAI,2020-07-19,GOOD,2020.0,7.0,19.0,Sunday,3.0,July,True,6.0
7,108,Anjali,31,45000,MARKETING,CHENNAI,2023-01-10,AVERAGE,2023.0,1.0,10.0,Tuesday,1.0,January,False,3.0
8,109,Vijay,27,39000,HR,PUNE,2024-03-15,EXCELLENT,2024.0,3.0,15.0,Friday,1.0,March,False,2.0
10,110,Deepa,28,41000,IT,DELHI,2022-09-01,AVERAGE,2022.0,9.0,1.0,Thursday,3.0,September,False,4.0
11,111,Arun,26,44000,MARKETING,CHENNAI,2023-11-10,GOOD,2023.0,11.0,10.0,Friday,4.0,November,False,3.0
12,112,Rahul,30,48000,FINANCE,MUMBAI,2023-01-10,POOR,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
13,113,Meena,-5,46000,HR,HYD,2020-10-30,AVERAGE,2020.0,10.0,30.0,Friday,4.0,October,False,6.0
14,114,Rohit,32,44000,IT,DELHI,2024-01-05,GOOD,2024.0,1.0,5.0,Friday,1.0,January,False,2.0

In [ ]:
df3 = df2.copy()

In [ ]:
df3

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance,Joining_Year,Joining_Month,Joining_Day,Weekday,Quarter,Month_Name,Is_Weekend,Years_of_Service
0,101,Rahul,25,35000,HR,HYD,2023-01-10,EXCELLENT,2023.0,1.0,10.0,Tuesday,1.0,January,False,3.0
1,102,Priya,28,42000,IT,HYD,2023-01-10,GOOD,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
2,103,Amit,28,44000,FINANCE,MUMBAI,2023-01-10,AVERAGE,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
3,104,Rahul,35,50000,HR,DELHI,2021-12-05,EXCELLENT,2021.0,12.0,5.0,Sunday,4.0,December,True,5.0
4,105,Sneha,29,47000,IT,DELHI,2023-01-10,POOR,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
5,106,Rahul,25,35000,HR,HYD,2023-01-10,EXCELLENT,2023.0,1.0,10.0,Tuesday,1.0,January,False,3.0
6,107,Kiran,150,999999,FINANCE,MUMBAI,2020-07-19,GOOD,2020.0,7.0,19.0,Sunday,3.0,July,True,6.0
7,108,Anjali,31,45000,MARKETING,CHENNAI,2023-01-10,AVERAGE,2023.0,1.0,10.0,Tuesday,1.0,January,False,3.0
8,109,Vijay,27,39000,HR,PUNE,2024-03-15,EXCELLENT,2024.0,3.0,15.0,Friday,1.0,March,False,2.0
10,110,Deepa,28,41000,IT,DELHI,2022-09-01,AVERAGE,2022.0,9.0,1.0,Thursday,3.0,September,False,4.0
11,111,Arun,26,44000,MARKETING,CHENNAI,2023-11-10,GOOD,2023.0,11.0,10.0,Friday,4.0,November,False,3.0
12,112,Rahul,30,48000,FINANCE,MUMBAI,2023-01-10,POOR,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
13,113,Meena,-5,46000,HR,HYD,2020-10-30,AVERAGE,2020.0,10.0,30.0,Friday,4.0,October,False,6.0
14,114,Rohit,32,44000,IT,DELHI,2024-01-05,GOOD,2024.0,1.0,5.0,Friday,1.0,January,False,2.0

In [ ]:
df3["Joining_Year"] = df3["Joining_Date"].dt.year
df3["Joining_Month"] = df3["Joining_Date"].dt.month
df3["Joining_Day"] = df3["Joining_Date"].dt.day
df3["Weekday"] = df3["Joining_Date"].dt.day_name()
df3["Quarter"] = df3["Joining_Date"].dt.quarter
df3["Month_Name"] = df3["Joining_Date"].dt.month_name()
df3["Is_Weekend"] = df3["Joining_Date"].dt.dayofweek >= 5

current_year = pd.Timestamp.now().year
df3["Years_of_Service"] = current_year - df3["Joining_Year"]

In [ ]:
df3

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance,Joining_Year,Joining_Month,Joining_Day,Weekday,Quarter,Month_Name,Is_Weekend,Years_of_Service
0,101,Rahul,25,35000,HR,HYD,2023-01-10,EXCELLENT,2023,1,10,Tuesday,1,January,False,3
1,102,Priya,28,42000,IT,HYD,2023-01-10,GOOD,2023,1,10,Tuesday,1,January,False,3
2,103,Amit,28,44000,FINANCE,MUMBAI,2023-01-10,AVERAGE,2023,1,10,Tuesday,1,January,False,3
3,104,Rahul,35,50000,HR,DELHI,2021-12-05,EXCELLENT,2021,12,5,Sunday,4,December,True,5
4,105,Sneha,29,47000,IT,DELHI,2023-01-10,POOR,2023,1,10,Tuesday,1,January,False,3
5,106,Rahul,25,35000,HR,HYD,2023-01-10,EXCELLENT,2023,1,10,Tuesday,1,January,False,3
6,107,Kiran,150,999999,FINANCE,MUMBAI,2020-07-19,GOOD,2020,7,19,Sunday,3,July,True,6
7,108,Anjali,31,45000,MARKETING,CHENNAI,2023-01-10,AVERAGE,2023,1,10,Tuesday,1,January,False,3
8,109,Vijay,27,39000,HR,PUNE,2024-03-15,EXCELLENT,2024,3,15,Friday,1,March,False,2
10,110,Deepa,28,41000,IT,DELHI,2022-09-01,AVERAGE,2022,9,1,Thursday,3,September,False,4
11,111,Arun,26,44000,MARKETING,CHENNAI,2023-11-10,GOOD,2023,11,10,Friday,4,November,False,3
12,112,Rahul,30,48000,FINANCE,MUMBAI,2023-01-10,POOR,2023,1,10,Tuesday,1,January,False,3
13,113,Meena,-5,46000,HR,HYD,2020-10-30,AVERAGE,2020,10,30,Friday,4,October,False,6
14,114,Rohit,32,44000,IT,DELHI,2024-01-05,GOOD,2024,1,5,Friday,1,January,False,2

In [ ]:
# ==========================================
# Check Column Names
# ==========================================

print(df3.columns)

Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City',
       'Joining_Date', 'Performance', 'Joining_Year', 'Joining_Month',
       'Joining_Day', 'Weekday', 'Quarter', 'Month_Name', 'Is_Weekend',
       'Years_of_Service'],
      dtype='object')

In [ ]:
# ==========================================
# Verify Data Types
# ==========================================

df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 14
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       14 non-null     int64
 1   Name              14 non-null     object
 2   Age               14 non-null     int64
 3   Salary            14 non-null     int64
 4   Department        14 non-null     category
 5   City              14 non-null     category
 6   Joining_Date      14 non-null     datetime64[ns]
 7   Performance       14 non-null     category
 8   Joining_Year      14 non-null     int32
 9   Joining_Month     14 non-null     int32
 10  Joining_Day       14 non-null     int32
 11  Weekday           14 non-null     object
 12  Quarter           14 non-null     int32
 13  Month_Name        14 non-null     object
 14  Is_Weekend        14 non-null     bool
 15  Years_of_Service  14 non-null     int32
dtypes: bool(1), category(3), datetime64[ns](1), int32(5), int64(3), object(3)
memory usage: 1.8+ KB

###Part 7: Dataset Validation
- Verify the cleaned dataset.
- Check the final dataset structure.
- Validate data types.
- Confirm the dataset is ready for Machine Learning.

###Part 8: Export Cleaned Dataset
- Save the cleaned dataset as a CSV file.
- Save the cleaned dataset as an Excel file.

In [ ]:
# ==========================================
# Display First Five Rows
# ==========================================

print(df3.head())

# ==========================================
# Display Last Five Rows
# ==========================================

print(df3.tail())

# ==========================================
# Dataset Shape
# ==========================================

print("Dataset Shape:", df3.shape)

# ==========================================
# Data Types
# ==========================================

print("Data types:")
print(df3.dtypes)

# ==========================================
# Dataset Information
# ==========================================

print("Dataset Information:")
df3.info()

# ==========================================
# Missing Values
# ==========================================

print("Missing Values:")
print(df3.isnull().sum())

# ==========================================
# Duplicate Records
# ==========================================

print("Duplicate Records:", df3.duplicated().sum())

# ==========================================
# Summary Statistics
# ==========================================

print("Summary Statistics:")
df3.describe(include="all")

# ==========================================
# Column Names
# ==========================================

print("Column Names:")
print(df3.columns)

# ==========================================
# Unique Values
# ==========================================

print("Unique Values:")
print("Department")

print(df3["Department"].unique())

print()

print("City")

print(df3["City"].unique())

print()

print("Performance")

print(df3["Performance"].unique())

   Employee_ID   Name  Age  Salary Department    City Joining_Date  \
0          101  Rahul   25   35000         HR     HYD   2023-01-10
1          102  Priya   28   42000         IT     HYD   2023-01-10
2          103   Amit   28   44000    FINANCE  MUMBAI   2023-01-10
3          104  Rahul   35   50000         HR   DELHI   2021-12-05
4          105  Sneha   29   47000         IT   DELHI   2023-01-10

  Performance  Joining_Year  Joining_Month  Joining_Day  Weekday  Quarter  \
0   EXCELLENT          2023              1           10  Tuesday        1
1        GOOD          2023              1           10  Tuesday        1
2     AVERAGE          2023              1           10  Tuesday        1
3   EXCELLENT          2021             12            5   Sunday        4
4        POOR          2023              1           10  Tuesday        1

  Month_Name  Is_Weekend  Years_of_Service
0    January       False                 3
1    January       False                 3
2    January       False                 3
3   December        True                 5
4    January       False                 3
    Employee_ID   Name  Age  Salary Department     City Joining_Date  \
10          110  Deepa   28   41000         IT    DELHI   2022-09-01
11          111   Arun   26   44000  MARKETING  CHENNAI   2023-11-10
12          112  Rahul   30   48000    FINANCE   MUMBAI   2023-01-10
13          113  Meena   -5   46000         HR      HYD   2020-10-30
14          114  Rohit   32   44000         IT    DELHI   2024-01-05

   Performance  Joining_Year  Joining_Month  Joining_Day   Weekday  Quarter  \
10     AVERAGE          2022              9            1  Thursday        3
11        GOOD          2023             11           10    Friday        4
12        POOR          2023              1           10   Tuesday        1
13     AVERAGE          2020             10           30    Friday        4
14        GOOD          2024              1            5    Friday        1

   Month_Name  Is_Weekend  Years_of_Service
10  September       False                 4
11   November       False                 3
12    January       False                 3
13    October       False                 6
14    January       False                 2
Dataset Shape: (14, 16)
Data types:
Employee_ID                  int64
Name                        object
Age                          int64
Salary                       int64
Department                category
City                      category
Joining_Date        datetime64[ns]
Performance               category
Joining_Year                 int32
Joining_Month                int32
Joining_Day                  int32
Weekday                     object
Quarter                      int32
Month_Name                  object
Is_Weekend                    bool
Years_of_Service             int32
dtype: object
Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 14
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       14 non-null     int64
 1   Name              14 non-null     object
 2   Age               14 non-null     int64
 3   Salary            14 non-null     int64
 4   Department        14 non-null     category
 5   City              14 non-null     category
 6   Joining_Date      14 non-null     datetime64[ns]
 7   Performance       14 non-null     category
 8   Joining_Year      14 non-null     int32
 9   Joining_Month     14 non-null     int32
 10  Joining_Day       14 non-null     int32
 11  Weekday           14 non-null     object
 12  Quarter           14 non-null     int32
 13  Month_Name        14 non-null     object
 14  Is_Weekend        14 non-null     bool
 15  Years_of_Service  14 non-null     int32
dtypes: bool(1), category(3), datetime64[ns](1), int32(5), int64(3), object(3)
memory usage: 1.8+ KB
Missing Values:
Employee_ID         0
Name                0
Age                 0
Salary              0
Department          0
City                0
Joining_Date        0
Performance         0
Joining_Year        0
Joining_Month       0
Joining_Day         0
Weekday             0
Quarter             0
Month_Name          0
Is_Weekend          0
Years_of_Service    0
dtype: int64
Duplicate Records: 0
Summary Statistics:
Column Names:
Index(['Employee_ID', 'Name', 'Age', 'Salary', 'Department', 'City',
       'Joining_Date', 'Performance', 'Joining_Year', 'Joining_Month',
       'Joining_Day', 'Weekday', 'Quarter', 'Month_Name', 'Is_Weekend',
       'Years_of_Service'],
      dtype='object')
Unique Values:
Department
['HR', 'IT', 'FINANCE', 'MARKETING']
Categories (4, object): ['FINANCE', 'HR', 'IT', 'MARKETING']

City
['HYD', 'MUMBAI', 'DELHI', 'CHENNAI', 'PUNE']
Categories (5, object): ['CHENNAI', 'DELHI', 'HYD', 'MUMBAI', 'PUNE']

Performance
['EXCELLENT', 'GOOD', 'AVERAGE', 'POOR']
Categories (4, object): ['AVERAGE', 'EXCELLENT', 'GOOD', 'POOR']

###Part 8: Export Cleaned Dataset
- Save the cleaned dataset as a CSV file.
- Save the cleaned dataset as an Excel file.

In [ ]:
# ==========================================
# Save Processed Employee Dataset as CSV
# ==========================================

df.to_csv("processed_employee_dataset.csv", index=False)

print("CSV file saved successfully.")

CSV file saved successfully.

In [ ]:
# ==========================================
# Save Processed Employee Dataset as Excel
# ==========================================

df.to_excel("processed_employee_dataset.xlsx", index=False)

print("Excel file saved successfully.")

Excel file saved successfully.

In [ ]:
from google.colab import files

files.download("processed_employee_dataset.csv")

files.download("processed_employee_dataset.xlsx")

In [ ]:
verification_df = pd.read_csv("processed_employee_dataset.csv")

verification_df.head()

,Employee_ID,Name,Age,Salary,Department,City,Joining_Date,Performance
0,101,Rahul,27,38500,Human Resources,Hyderabad,2023-01-10,Excellent
1,102,Priya,30,46200,Information Technology,hyderabad,2022/05/14,Good
2,103,Amit,30,48400,Finance,Mumbai,15-08-2021,Average
3,104,Rahul,38,55000,Human Resources,Delhi,2021-12-05,Excellent
4,105,Sneha,31,51700,Information Technology,Delhi,Invalid Date,Poor