In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}

df = pd.DataFrame(data)
df

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [ ]:
df.head()

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi

In [ ]:
print(df.head())

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes
None

In [ ]:
print(df.describe())

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

In [ ]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False  False
4   True  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False

In [ ]:
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [ ]:
df_Drop = df.dropna()
df_Drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Name']=df['Name'].fillna(df['Name'].mode()[0])

In [ ]:
df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Mumbai", "Delhi", "Pune", "Mumbai","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Mumbai
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0  Mumbai
4  20.0  20000.0  Mumbai

In [ ]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Mumbai
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0  Mumbai
4  20.00  20000.0  Mumbai

In [ ]:
df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)
df

   Age  Salary    City
0   20   20000  Mumbai
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000  Mumbai
4   20   20000  Mumbai

In [ ]:
df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)
df

     Age   Salary    City
0  24.20  24200.0  Mumbai
1  27.83  30250.0   Delhi
2  30.25  31762.5    Pune
3  36.30  48400.0  Mumbai
4  24.20  24200.0  Mumbai

In [ ]:
df[["City"]] = df[["City"]].replace('Mumbai','MUMBAI')
df

     Age   Salary    City
0  24.20  24200.0  MUMBAI
1  27.83  30250.0   Delhi
2  30.25  31762.5    Pune
3  36.30  48400.0  MUMBAI
4  24.20  24200.0  MUMBAI

In [ ]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

     Age   Salary  City_Delhi  City_MUMBAI  City_Pune
0  24.20  24200.0       False         True      False
1  27.83  30250.0        True        False      False
2  30.25  31762.5       False        False       True
3  36.30  48400.0       False         True      False
4  24.20  24200.0       False         True      False

In [ ]:
df_drop = df.drop_duplicates()
df

     Age   Salary    City
0  24.20  24200.0  MUMBAI
1  27.83  30250.0   Delhi
2  30.25  31762.5    Pune
3  36.30  48400.0  MUMBAI
4  24.20  24200.0  MUMBAI

In [ ]:
df["City"] = df["City"].str.upper()
df

     Age   Salary    City
0  24.20  24200.0  MUMBAI
1  27.83  30250.0   DELHI
2  30.25  31762.5    PUNE
3  36.30  48400.0  MUMBAI
4  24.20  24200.0  MUMBAI

In [ ]:
df2 = df.dropna()
df2

     Age   Salary    City
0  24.20  24200.0  MUMBAI
1  27.83  30250.0   DELHI
2  30.25  31762.5    PUNE
3  36.30  48400.0  MUMBAI
4  24.20  24200.0  MUMBAI

# 🌧️ Rainfall Dataset Cleaning

## 🎯 Objective:
Clean and preprocess the dataset `rainfall.csv`

---

## 🔹 Dataset Columns:
- date
- rainfall
- temperature
- humidity
- wind_speed
- weather_condition

---

## ⚠️ Possible Issues:
- Date format not parsed
- Missing values (if any)
- Inconsistent text (Rainy / rainy)
- Wrong data types
- Outliers

---

## ✅ Steps We Will Perform:
1. Load dataset
2. Convert date column
3. Handle missing values
4. Fix text inconsistencies
5. Remove duplicates
6. Detect & handle outliers
7. Final clean dataset

## 📤 Upload CSV File from Local System (Google Colab)

Since the file is on your computer, we need to upload it manually.

---

## 🔹 Steps:
1. Run the cell below
2. Click "Choose Files"
3. Select `rainfall.csv`
4. File will be uploaded to Colab environment

---

After uploading, we can load it using pandas.

In [ ]:
from google.colab import files

uploaded = files.upload()

# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

Saving rainfall.csv to rainfall.csv
Uploaded file: rainfall.csv

## 🔧 Data Cleaning Operations on rainfall.csv

After uploading and loading the dataset, we perform:

---

### ✅ Operations:
1. Inspect data
2. Convert date column
3. Handle missing values
4. Fix text inconsistencies
5. Remove duplicates
6. Handle outliers
7. Feature engineering
8. Encoding categorical data
9. Save cleaned dataset

---

Each step is important for ML readiness.

In [ ]:
df.head()

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

date                 0
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

## 🔹 Convert Date Column

Convert string → datetime format

---

Helps in:
- Sorting
- Time-based analysis

In [ ]:
df["date"] = df["date"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     datetime64[ns]
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.7+ KB

## 🔹 Handle Missing Values

### Numerical Columns:
- rainfall
- temperature
- humidity
- wind_speed

➡️ Fill with mean

### Categorical:
- weather_condition

➡️ Fill with mode

In [ ]:
import pandas as pd

# Numerical columns
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

# Check missing values
print(df.isnull().sum())

date                 1
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

## 🔹 Fix Text Inconsistency

Standardize text:
- Rainy → rainy
- SUNNY → sunny

In [ ]:
df["weather_condition"] = df["weather_condition"].str.lower()

df["weather_condition"].unique()

df

         date   rainfall  temperature   humidity  wind_speed weather_condition
0  2022-01-01  12.500000    15.200000  78.000000    8.500000             rainy
1  2022-01-02   8.200000    17.800000  65.000000    5.200000             rainy
2  2022-01-03   0.000000    20.100000  52.000000    3.100000             sunny
3  2022-01-04   3.700000    18.600000  71.000000    6.700000             rainy
4  2022-01-05  21.100000    14.800000  82.000000    9.300000             rainy
5  2022-01-06  15.300000    16.500000  75.000000    7.800000             rainy
6  2022-01-07   6.800000    19.200000  61.000000    4.500000             rainy
7  2022-01-08   0.000000    21.700000  48.000000    2.900000             sunny
8  2022-01-09  11.200000    17.300000  73.000000    6.100000             rainy
9  2022-01-10  18.600000    15.800000  79.000000    8.900000             rainy
10 2022-01-11   9.500000    16.200000  72.000000    5.700000             rainy
11 2022-01-12   2.100000    19.800000  58.000000    3.500000             rainy
12 2022-01-13   0.000000    22.400000  45.000000    2.100000             sunny
13 2022-01-14   7.400000    17.900000  69.000000    6.500000             rainy
14 2022-01-15  14.900000    15.100000  81.000000    8.700000             rainy
15 2022-01-16  19.200000    16.800000  77.000000    7.200000             rainy
16 2022-01-17   5.600000    18.500000  63.000000    4.900000             rainy
17 2022-01-18   0.000000    21.200000  51.000000    3.300000             sunny
18 2022-01-19  10.800000    17.600000  75.000000    6.700000             rainy
19 2022-01-20  16.300000    14.500000  84.000000    9.100000             rainy
20 2022-01-21   3.900000    16.100000  71.000000    5.300000             rainy
21 2022-01-22   0.000000    19.400000  59.000000    4.100000             sunny
22 2022-01-23   7.100000    18.200000  67.000000    7.100000             rainy
23 2022-01-24  12.700000    15.700000  79.000000    8.300000             rainy
24 2022-01-25  18.400000    17.100000  76.000000    6.800000             rainy
25 2022-01-26   9.800000    19.700000  62.000000    4.700000             rainy
26 2022-01-27   0.000000    22.900000  47.000000    2.500000             sunny
27 2022-01-28   6.200000    18.500000  70.000000    7.300000             rainy
28 2022-01-29  15.500000    14.200000  83.000000    9.500000             rainy
29 2022-01-30  21.800000    16.400000  78.000000    7.600000             rainy
30 2022-01-31  11.600000    19.100000  65.000000    5.100000             rainy
31 2022-02-01   0.000000    21.600000  53.000000    3.700000             sunny
32 2022-02-02   4.300000    17.200000  73.000000    7.500000             rainy
33 2022-02-03   9.100000    15.400000  81.000000    8.900000             rainy
34 2022-02-04  17.900000    16.700000  77.000000    6.200000             rainy
35 2022-02-05   7.500000    18.900000  64.000000    4.300000             rainy
36 2022-02-06   0.000000    22.100000  49.000000    2.700000             sunny
37 2022-02-07   5.800000    17.800000  72.000000    6.900000             rainy
38 2022-02-08  13.200000    14.700000  85.000000    9.300000             rainy
39 2022-02-09  19.600000    16.200000  79.000000    7.800000             rainy
40 2022-02-10  10.400000    19.500000  66.000000    5.500000             rainy
41 2022-02-11   0.000000    23.400000  44.000000    3.100000             sunny
42 2022-02-12   6.700000    18.100000  74.000000    7.700000             rainy
43 2022-02-13  14.800000    13.900000  87.000000    9.900000             rainy
44 2022-02-14  20.500000    15.600000  81.000000    8.200000             rainy
45 2022-02-15   8.300000    19.200000  68.000000    6.100000             rainy
46 2022-02-16   0.000000    22.700000  51.000000    4.500000             sunny
47 2022-02-17   5.100000    17.400000  75.000000    8.300000             rainy
48 2022-02-18  11.900000    14.100000  89.000000   10.500000             rainy
49 2022-02-19  17.300000    15.900000  83.000000    8.600000             rainy
50 2022-02-20   9.600000    18.600000  71.000000    6.700000             rainy
51 2022-02-21   0.000000    21.300000  55.000000    5.100000             sunny
52 2022-02-22   7.400000    16.800000  77.000000    8.900000             rainy
53        NaT   9.049057    17.950943  69.245283    6.403774             rainy

In [ ]:
df.to_csv("cleaned_rainfall.csv", index=False)

In [1]:
import pandas as pd
import numpy as np

data = {
    "date": [
        "2024-01-01",
        "2024/01/02",
        "2024-01-03",
        "2024-01-03",
        None,
        "2024-01-06",
        "2024-01-07",
        "2024-01-08"
    ],
    "rainfall": [
        12.5,
        15.2,
        np.nan,
        15.2,
        250,
        18.4,
        10.1,
        12.5
    ],
    "temperature": [
        28,
        30,
        29,
        29,
        np.nan,
        31,
        28,
        28
    ],
    "humidity": [
        75,
        np.nan,
        80,
        80,
        78,
        76,
        74,
        75
    ],
    "wind_speed": [
        12,
        14,
        13,
        13,
        15,
        np.nan,
        11,
        12
    ],
    "weather_condition": [
        "Rainy",
        "rainy",
        "Sunny",
        "Sunny",
        None,
        "Cloudy",
        "RAINY",
        "Rainy"
    ]
}

df = pd.DataFrame(data)

df

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2024-01-01      12.5         28.0      75.0        12.0             Rainy
1  2024/01/02      15.2         30.0       NaN        14.0             rainy
2  2024-01-03       NaN         29.0      80.0        13.0             Sunny
3  2024-01-03      15.2         29.0      80.0        13.0             Sunny
4        None     250.0          NaN      78.0        15.0              None
5  2024-01-06      18.4         31.0      76.0         NaN            Cloudy
6  2024-01-07      10.1         28.0      74.0        11.0             RAINY
7  2024-01-08      12.5         28.0      75.0        12.0             Rainy

Part 1: Import Libraries

In [2]:
import pandas as pd
import numpy as np

Part 2: Load Dataset

Part 3: Inspect Dataset

In [3]:
print(df.head())

print(df.info())

print(df.describe())

print(df.isnull().sum())

print("Duplicate Records:", df.duplicated().sum())

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2024-01-01      12.5         28.0      75.0        12.0             Rainy
1  2024/01/02      15.2         30.0       NaN        14.0             rainy
2  2024-01-03       NaN         29.0      80.0        13.0             Sunny
3  2024-01-03      15.2         29.0      80.0        13.0             Sunny
4        None     250.0          NaN      78.0        15.0              None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               7 non-null      object
 1   rainfall           7 non-null      float64
 2   temperature        7 non-null      float64
 3   humidity           7 non-null      float64
 4   wind_speed         7 non-null      float64
 5   weather_condition  7 non-null      object
dtypes: float64(4), object(2)
memory usage: 516.0+ bytes
None
         rainfall  temperature   humidity  wind_speed
count    7.000000     7.000000   7.000000    7.000000
mean    47.700000    29.000000  76.857143   12.857143
std     89.245093     1.154701   2.478479    1.345185
min     10.100000    28.000000  74.000000   11.000000
25%     12.500000    28.000000  75.000000   12.000000
50%     15.200000    29.000000  76.000000   13.000000
75%     16.800000    29.500000  79.000000   13.500000
max    250.000000    31.000000  80.000000   15.000000
date                 1
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64
Duplicate Records: 0

Part 4: Convert Date Column

In [4]:
df["date"] = df["date"].astype(str).str.strip()

df["date"] = pd.to_datetime(df["date"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               6 non-null      datetime64[ns]
 1   rainfall           7 non-null      float64
 2   temperature        7 non-null      float64
 3   humidity           7 non-null      float64
 4   wind_speed         7 non-null      float64
 5   weather_condition  7 non-null      object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 516.0+ bytes

Part 5: Handle Missing Values

In [5]:
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

print(df.isnull().sum())

date                 2
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

Part 6: Fix Text Inconsistencies

In [6]:
df["weather_condition"] = df["weather_condition"].str.lower().str.strip()

print(df["weather_condition"].unique())

['rainy' 'sunny' 'cloudy']

Part 7: Remove Duplicates

In [7]:
print("Before:", df.duplicated().sum())

df = df.drop_duplicates()

print("After:", df.duplicated().sum())

Before: 0
After: 0

Part 8: Detect Outliers (IQR)

In [8]:
Q1 = df["rainfall"].quantile(0.25)
Q3 = df["rainfall"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["rainfall"] < lower) | (df["rainfall"] > upper)]

print(outliers)

        date  rainfall  temperature  humidity  wind_speed weather_condition
2 2024-01-03      47.7         29.0      80.0        13.0             sunny
4        NaT     250.0         29.0      78.0        15.0             rainy

Part 9: Handle Outliers

In [9]:
median = df["rainfall"].median()

df["rainfall"] = np.where(df["rainfall"] < lower, median, df["rainfall"])
df["rainfall"] = np.where(df["rainfall"] > upper, median, df["rainfall"])

df.head()

        date  rainfall  temperature   humidity  wind_speed weather_condition
0 2024-01-01      12.5         28.0  75.000000        12.0             rainy
1        NaT      15.2         30.0  76.857143        14.0             rainy
2 2024-01-03      15.2         29.0  80.000000        13.0             sunny
3 2024-01-03      15.2         29.0  80.000000        13.0             sunny
4        NaT      15.2         29.0  78.000000        15.0             rainy

Part 10: Validate Dataset

In [10]:
print(df.info())

print(df.isnull().sum())

print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               6 non-null      datetime64[ns]
 1   rainfall           8 non-null      float64
 2   temperature        8 non-null      float64
 3   humidity           8 non-null      float64
 4   wind_speed         8 non-null      float64
 5   weather_condition  8 non-null      object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 516.0+ bytes
None
date                 2
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64
1

Part 11: Save Dataset

In [11]:
df.to_csv("cleaned_rainfall.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

## 🔹 Basic Questions

1. Load a CSV file and display:
   - First 5 rows
   - Last 5 rows

2. Find:
   - Total number of rows & columns
   - Data types of each column

3. Identify missing values:
   - Which columns have missing values?
   - Count them

4. Fill missing values:
   - Numerical → mean
   - Categorical → mode

5. Remove duplicate rows

6. Convert a column:
   - "date" → datetime format

7. Rename columns:
   - Change column names to lowercase

8. Change data type:
   - Convert float → int (where applicable)

## 🔹 Intermediate Questions

1. Select multiple columns and:
   - Fill missing values together

2. Apply transformation:
   - Increase salary/marks by 10%

3. Fix inconsistent text:
   - "Mumbai", "mumbai", "MUMBAI" → one format

4. Create new column:
   - Example: "Pass/Fail" based on marks

5. Filter data:
   - Students with marks > 80
   - Rainfall > 10

6. Drop unnecessary columns:
   - Based on relevance

7. Apply One-Hot Encoding:
   - On categorical columns

8. Sort dataset:
   - Based on date or marks