# 🎓 Student Performance Dataset – Data Cleaning

## 🎯 Objective:
Clean and preprocess student dataset for ML

---

## 🔹 Columns:
- name
- age
- gender
- marks
- attendance
- city

---

## ⚠️ Possible Issues:
- Missing values
- Inconsistent text (Male / male)
- Invalid marks (>100 or <0)
- Duplicates

In [ ]:
import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
2  John   NaN    Male    105        80.0  mumbai
3  Amit  20.0    Male     85        90.0  Mumbai
4  None  19.0  FEMALE     -5         NaN    Pune

In [ ]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      int64
 4   attendance  4 non-null      float64
 5   city        5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

             age       marks  attendance
count   4.000000    5.000000    4.000000
mean   20.000000   72.000000   86.250000
std     0.816497   43.817805    4.787136
min    19.000000   -5.000000   80.000000
25%    19.750000   85.000000   83.750000
50%    20.000000   85.000000   87.500000
75%    20.250000   90.000000   90.000000
max    21.000000  105.000000   90.000000

## 🔹 Handling Missing Values

- age → mean
- attendance → mean
- name → "Unknown"

In [ ]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

/tmp/ipykernel_433/1440735091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipykernel_433/1440735091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["attendance"].fillna(df["attendance"].mean(), inplace=True)
/tmp/ipykernel_433/1440735091.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace=True)

      name   age  gender  marks  attendance    city
0     Amit  20.0    Male     85       90.00  Mumbai
1     Sara  21.0  female     90       85.00   Delhi
2     John  20.0    Male    105       80.00  mumbai
3     Amit  20.0    Male     85       90.00  Mumbai
4  Unknown  19.0  FEMALE     -5       86.25    Pune

In [ ]:
df["gender"] = df["gender"].str.lower()
df["city"] = df["city"].str.lower()

df

      name   age  gender  marks  attendance    city
0     Amit  20.0    male     85       90.00  mumbai
1     Sara  21.0  female     90       85.00   delhi
2     John  20.0    male    105       80.00  mumbai
3     Amit  20.0    male     85       90.00  mumbai
4  Unknown  19.0  female     -5       86.25    pune

## 🔹 Fix Invalid Data

Marks should be:
- Between 0 and 100

In [ ]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df

   name   age  gender  marks  attendance    city
0  Amit  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai

In [ ]:
import pandas as pd
import numpy as np

data = {
    "name": [
        "Rahul",
        "Priya",
        "Amit",
        "Sneha",
        "Rahul",
        None,
        "Kiran",
        "Anjali"
    ],
    "age": [
        20,
        21,
        np.nan,
        19,
        20,
        22,
        21,
        20
    ],
    "gender": [
        "Male",
        "male",
        "Female",
        "FEMALE",
        "Male",
        None,
        "Female",
        "female"
    ],
    "marks": [
        85,
        92,
        105,
        -5,
        85,
        76,
        np.nan,
        88
    ],
    "attendance": [
        90,
        np.nan,
        85,
        95,
        90,
        88,
        92,
        91
    ],
    "city": [
        "Hyderabad",
        "hyderabad",
        "Delhi",
        "Mumbai",
        "Hyderabad",
        None,
        "DELHI",
        "Mumbai"
    ]
}

df = pd.DataFrame(data)

df

     name   age  gender  marks  attendance       city
0   Rahul  20.0    Male   85.0        90.0  Hyderabad
1   Priya  21.0    male   92.0         NaN  hyderabad
2    Amit   NaN  Female  105.0        85.0      Delhi
3   Sneha  19.0  FEMALE   -5.0        95.0     Mumbai
4   Rahul  20.0    Male   85.0        90.0  Hyderabad
5    None  22.0    None   76.0        88.0       None
6   Kiran  21.0  Female    NaN        92.0      DELHI
7  Anjali  20.0  female   88.0        91.0     Mumbai

Part 1: Import Libraries

In [ ]:
import pandas as pd
import numpy as np

Part 2: Load Dataset ,

Part 3: Inspect Dataset

In [ ]:
print(df.head())

print(df.info())

print(df.describe())

print(df.isnull().sum())

print("Duplicate Records:", df.duplicated().sum())

    name   age  gender  marks  attendance       city
0  Rahul  20.0    Male   85.0        90.0  Hyderabad
1  Priya  21.0    male   92.0         NaN  hyderabad
2   Amit   NaN  Female  105.0        85.0      Delhi
3  Sneha  19.0  FEMALE   -5.0        95.0     Mumbai
4  Rahul  20.0    Male   85.0        90.0  Hyderabad
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        7 non-null      object
 1   age         7 non-null      float64
 2   gender      7 non-null      object
 3   marks       7 non-null      float64
 4   attendance  7 non-null      float64
 5   city        7 non-null      object
dtypes: float64(3), object(3)
memory usage: 516.0+ bytes
None
             age       marks  attendance
count   7.000000    7.000000    7.000000
mean   20.428571   75.142857   90.142857
std     0.975900   36.420821    3.132016
min    19.000000   -5.000000   85.000000
25%    20.000000   80.500000   89.000000
50%    20.000000   85.000000   90.000000
75%    21.000000   90.000000   91.500000
max    22.000000  105.000000   95.000000
name          1
age           1
gender        1
marks         1
attendance    1
city          1
dtype: int64
Duplicate Records: 1

Part 4: Handle Missing Values

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean())

df["marks"] = df["marks"].fillna(df["marks"].mean())

df["attendance"] = df["attendance"].fillna(df["attendance"].mean())

df["gender"] = df["gender"].fillna(df["gender"].mode()[0])

df["city"] = df["city"].fillna(df["city"].mode()[0])

print(df.isnull().sum())

name          1
age           0
gender        0
marks         0
attendance    0
city          0
dtype: int64

Part 5: Fix Text Inconsistencies

In [ ]:
df["gender"] = df["gender"].str.lower().str.strip()

df["city"] = df["city"].str.title().str.strip()

print(df["gender"].unique())

print(df["city"].unique())

['male' 'female']
['Hyderabad' 'Delhi' 'Mumbai']

Part 6: Remove Invalid Marks

In [ ]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df.head()

    name   age  gender      marks  attendance       city
0  Rahul  20.0    male  85.000000   90.000000  Hyderabad
1  Priya  21.0    male  92.000000   90.142857  Hyderabad
4  Rahul  20.0    male  85.000000   90.000000  Hyderabad
5   None  22.0  female  76.000000   88.000000  Hyderabad
6  Kiran  21.0  female  75.142857   92.000000      Delhi

Part 7: Remove Duplicate Records

In [ ]:
print("Before:", df.duplicated().sum())

df = df.drop_duplicates()

print("After:", df.duplicated().sum())

Before: 1
After: 0

Part 8: Validate Dataset

In [ ]:
print(df.info())

print(df.isnull().sum())

print(df.duplicated().sum())

print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         5 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      float64
 4   attendance  5 non-null      float64
 5   city        5 non-null      object
dtypes: float64(3), object(3)
memory usage: 280.0+ bytes
None
name          1
age           0
gender        0
marks         0
attendance    0
city          0
dtype: int64
0
            age      marks  attendance
count   5.00000   5.000000    5.000000
mean   20.80000  83.228571   90.228571
std     0.83666   7.424175    1.479796
min    20.00000  75.142857   88.000000
25%    20.00000  76.000000   90.000000
50%    21.00000  85.000000   90.142857
75%    21.00000  88.000000   91.000000
max    22.00000  92.000000   92.000000

Part 9 : Save Cleaned Dataset

In [ ]:
df.to_csv("cleaned_student_performance.csv", index=False)

print("Dataset Saved Successfully")

## 🔹 Basic Questions

1. Load a CSV file and display:
   - First 5 rows
   - Last 5 rows

2. Find:
   - Total number of rows & columns
   - Data types of each column

3. Identify missing values:
   - Which columns have missing values?
   - Count them

4. Fill missing values:
   - Numerical → mean
   - Categorical → mode

5. Remove duplicate rows

6. Convert a column:
   - "date" → datetime format

7. Rename columns:
   - Change column names to lowercase

8. Change data type:
   - Convert float → int (where applicable)

## 🔹 Intermediate Questions

1. Select multiple columns and:
   - Fill missing values together

2. Apply transformation:
   - Increase salary/marks by 10%

3. Fix inconsistent text:
   - "Mumbai", "mumbai", "MUMBAI" → one format

4. Create new column:
   - Example: "Pass/Fail" based on marks

5. Filter data:
   - Students with marks > 80
   - Rainfall > 10

6. Drop unnecessary columns:
   - Based on relevance

7. Apply One-Hot Encoding:
   - On categorical columns

8. Sort dataset:
   - Based on date or marks