# 📊 Feature Engineering – Practice Assignment

## 🎯 Objective
Apply feature engineering techniques on a dataset to prepare it for machine learning.

---

## 📁 Dataset
Use any dataset with columns like:
- Age
- Salary
- Gender
- City
- Date
- Purchase_Amount
- Experience
- Rating

---

## 🧠 Instructions
- Perform each task using Python (Pandas, NumPy, Sklearn)
- Write clean and readable code
- Display output after each step

---

# 🔹 Problem 1: Handling Missing Values
Fill missing values:
- Numerical columns → Mean
- Categorical columns → Mode

👉 Output: Dataset with no missing values

---

# 🔹 Problem 2: Feature Scaling
- Apply Standardization on Salary
- Apply Min-Max Scaling on Age

👉 Compare before and after values

---

# 🔹 Problem 3: Encoding Categorical Data
- Apply Label Encoding on Gender
- Apply One-Hot Encoding on City

👉 Output transformed dataset

---

# 🔹 Problem 4: Feature Creation
Create a new column:
Total_Spending = Salary + Purchase_Amount

👉 Analyze how it changes the dataset

---

# 🔹 Problem 5: Date Feature Extraction
From Date column extract:
- Year
- Month
- Day
- Weekday

👉 Add new columns

---

# 🔹 Problem 6: Binning
Convert Age into categories:
- 0–25 → Young
- 26–45 → Adult
- 46+ → Senior

👉 Create Age_Group column

---

# 🔹 Problem 7: Outlier Detection
Detect outliers in Salary using IQR method

👉 Display only outlier rows

---

# 🔹 Problem 8: Feature Interaction
Create a new feature:
Experience_Salary = Experience * Salary

👉 Explain its importance

---

# 🔹 Problem 9: Feature Selection
- Find correlation of all features with Purchase_Amount
- Drop least important feature

👉 Show final dataset

---

#
- Ensure all outputs are visible

Import Libraries

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder


Create Dataset

In [ ]:
data = {
    "Age": [22, 35, np.nan, 45, 52, 28, 31, np.nan, 40, 60],
    "Salary": [30000, 50000, 45000, np.nan, 120000, 38000, 42000, 46000, 55000, 500000],
    "Gender": ["Male", "Female", "Female", "Male", None, "Female", "Male", "Female", "Male", "Male"],
    "City": ["Hyderabad", "Delhi", "Mumbai", "Pune", "Delhi", "Hyderabad", None, "Mumbai", "Pune", "Delhi"],
    "Date": [
        "2023-01-15",
        "2022-05-10",
        "2021-08-25",
        "2023-03-18",
        "2020-12-05",
        "2022-11-20",
        "2021-07-09",
        "2023-06-30",
        "2022-09-14",
        "2020-01-01"
    ],
    "Purchase_Amount": [5000, 7000, 6500, 8000, 15000, 6000, 7500, 6800, 7200, 25000],
    "Experience": [1, 5, 4, 8, 15, 3, 6, 5, 7, 25],
    "Rating": [4.5, 4.2, 3.8, 4.7, 4.9, 3.9, 4.1, 4.0, 4.3, 5.0]
}

df = pd.DataFrame(data)

df

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,22.0,30000.0,Male,Hyderabad,2023-01-15,5000,1,4.5
1,35.0,50000.0,Female,Delhi,2022-05-10,7000,5,4.2
2,NaN,45000.0,Female,Mumbai,2021-08-25,6500,4,3.8
3,45.0,NaN,Male,Pune,2023-03-18,8000,8,4.7
4,52.0,120000.0,None,Delhi,2020-12-05,15000,15,4.9
5,28.0,38000.0,Female,Hyderabad,2022-11-20,6000,3,3.9
6,31.0,42000.0,Male,None,2021-07-09,7500,6,4.1
7,NaN,46000.0,Female,Mumbai,2023-06-30,6800,5,4.0
8,40.0,55000.0,Male,Pune,2022-09-14,7200,7,4.3
9,60.0,500000.0,Male,Delhi,2020-01-01,25000,25,5.0

🔹 Problem 1 : Handling Missing Values

In [ ]:
print("Missing Values Before Filling")
print(df.isnull().sum())

Missing Values Before Filling
Age                2
Salary             1
Gender             1
City               1
Date               0
Purchase_Amount    0
Experience         0
Rating             0
dtype: int64

In [ ]:
# Numerical columns

num_cols = ["Age","Salary"]

df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [ ]:
# Categorical columns

cat_cols = ["Gender","City"]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
print("Missing Values After Filling")
print(df.isnull().sum())

df

Missing Values After Filling
Age                0
Salary             0
Gender             0
City               0
Date               0
Purchase_Amount    0
Experience         0
Rating             0
dtype: int64

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0

🔹 Problem 2 : Feature Scaling

In [ ]:
print("Before Standardization")
print(df["Salary"])

Before Standardization
0     30000.000000
1     50000.000000
2     45000.000000
3    102888.888889
4    120000.000000
5     38000.000000
6     42000.000000
7     46000.000000
8     55000.000000
9    500000.000000
Name: Salary, dtype: float64

In [ ]:
scaler = StandardScaler()

df["Salary_Standardized"] = scaler.fit_transform(df[["Salary"]])

df[["Salary","Salary_Standardized"]]

          Salary  Salary_Standardized
0   30000.000000            -0.538959
1   50000.000000            -0.391074
2   45000.000000            -0.428045
3  102888.888889             0.000000
4  120000.000000             0.126524
5   38000.000000            -0.479805
6   42000.000000            -0.450228
7   46000.000000            -0.420651
8   55000.000000            -0.354103
9  500000.000000             2.936341

In [ ]:
print("\nAfter Standardization")
print(df["Salary_Standardized"])

After Standardization
0   -0.538959
1   -0.391074
2   -0.428045
3    0.000000
4    0.126524
5   -0.479805
6   -0.450228
7   -0.420651
8   -0.354103
9    2.936341
Name: Salary_Standardized, dtype: float64

In [ ]:
print("Before Min-Max Scaling")
print(df["Age"])

Before Min-Max Scaling
0    22.000
1    35.000
2    39.125
3    45.000
4    52.000
5    28.000
6    31.000
7    39.125
8    40.000
9    60.000
Name: Age, dtype: float64

In [ ]:
minmax = MinMaxScaler()

df["Age_Normalized"] = minmax.fit_transform(df[["Age"]])

df[["Age","Age_Normalized"]]

      Age  Age_Normalized
0  22.000        0.000000
1  35.000        0.342105
2  39.125        0.450658
3  45.000        0.605263
4  52.000        0.789474
5  28.000        0.157895
6  31.000        0.236842
7  39.125        0.450658
8  40.000        0.473684
9  60.000        1.000000

In [ ]:
print("\nAfter Min-Max Scaling")
print(df["Age_Normalized"])

After Min-Max Scaling
0    0.000000
1    0.342105
2    0.450658
3    0.605263
4    0.789474
5    0.157895
6    0.236842
7    0.450658
8    0.473684
9    1.000000
Name: Age_Normalized, dtype: float64

🔹 Problem 3 : Encoding

In [ ]:
#Label Encoding

le = LabelEncoder()

df["Gender_Label"] = le.fit_transform(df["Gender"])

df

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5,-0.538959,0.000000,1
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2,-0.391074,0.342105,0
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8,-0.428045,0.450658,0
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7,0.000000,0.605263,1
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9,0.126524,0.789474,1
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9,-0.479805,0.157895,0
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1,-0.450228,0.236842,1
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0,-0.420651,0.450658,0
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3,-0.354103,0.473684,1
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.000000,1

In [ ]:
#One-Hot Encoding

df_encoded = pd.get_dummies(df,columns=["City"])

df_encoded

,Age,Salary,Gender,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,22.000,30000.000000,Male,2023-01-15,5000,1,4.5,-0.538959,0.000000,1,False,True,False,False
1,35.000,50000.000000,Female,2022-05-10,7000,5,4.2,-0.391074,0.342105,0,True,False,False,False
2,39.125,45000.000000,Female,2021-08-25,6500,4,3.8,-0.428045,0.450658,0,False,False,True,False
3,45.000,102888.888889,Male,2023-03-18,8000,8,4.7,0.000000,0.605263,1,False,False,False,True
4,52.000,120000.000000,Male,2020-12-05,15000,15,4.9,0.126524,0.789474,1,True,False,False,False
5,28.000,38000.000000,Female,2022-11-20,6000,3,3.9,-0.479805,0.157895,0,False,True,False,False
6,31.000,42000.000000,Male,2021-07-09,7500,6,4.1,-0.450228,0.236842,1,True,False,False,False
7,39.125,46000.000000,Female,2023-06-30,6800,5,4.0,-0.420651,0.450658,0,False,False,True,False
8,40.000,55000.000000,Male,2022-09-14,7200,7,4.3,-0.354103,0.473684,1,False,False,False,True
9,60.000,500000.000000,Male,2020-01-01,25000,25,5.0,2.936341,1.000000,1,True,False,False,False

🔹 Problem 4 : Feature Creation

In [ ]:
df["Total_Spending"] = df["Salary"] + df["Purchase_Amount"]

df

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5,-0.538959,0.000000,1,35000.000000
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2,-0.391074,0.342105,0,57000.000000
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8,-0.428045,0.450658,0,51500.000000
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7,0.000000,0.605263,1,110888.888889
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9,0.126524,0.789474,1,135000.000000
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9,-0.479805,0.157895,0,44000.000000
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1,-0.450228,0.236842,1,49500.000000
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0,-0.420651,0.450658,0,52800.000000
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3,-0.354103,0.473684,1,62200.000000
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.000000,1,525000.000000

Analysis:

- Total_Spending combines Salary and Purchase_Amount.
- It gives the overall financial spending capability of a person.
- Instead of using two separate features, the model can also learn from this combined feature.
- This may improve prediction accuracy in some machine learning problems.

🔹 Problem 5 : Date Feature Extraction

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.day_name()

df

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Month,Day,Weekday
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5,-0.538959,0.000000,1,35000.000000,2023,1,15,Sunday
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2,-0.391074,0.342105,0,57000.000000,2022,5,10,Tuesday
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8,-0.428045,0.450658,0,51500.000000,2021,8,25,Wednesday
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7,0.000000,0.605263,1,110888.888889,2023,3,18,Saturday
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9,0.126524,0.789474,1,135000.000000,2020,12,5,Saturday
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9,-0.479805,0.157895,0,44000.000000,2022,11,20,Sunday
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1,-0.450228,0.236842,1,49500.000000,2021,7,9,Friday
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0,-0.420651,0.450658,0,52800.000000,2023,6,30,Friday
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3,-0.354103,0.473684,1,62200.000000,2022,9,14,Wednesday
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.000000,1,525000.000000,2020,1,1,Wednesday

🔹 Problem 6 : Binning

In [ ]:
bins = [0,25,45,100]

labels = ["Young","Adult","Senior"]

df["Age_Group"] = pd.cut(df["Age"],
                         bins=bins,
                         labels=labels)

df[["Age","Age_Group"]]

      Age Age_Group
0  22.000     Young
1  35.000     Adult
2  39.125     Adult
3  45.000     Adult
4  52.000    Senior
5  28.000     Adult
6  31.000     Adult
7  39.125     Adult
8  40.000     Adult
9  60.000    Senior

🔹 Problem 7 : Outlier Detection using IQR

In [ ]:
Q1 = df["Salary"].quantile(0.25)

Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - (1.5 * IQR)

upper_limit = Q3 + (1.5 * IQR)

In [ ]:
outliers = df[(df["Salary"] < lower_limit) |
              (df["Salary"] > upper_limit)]

print("Outlier Rows")

outliers

Outlier Rows

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Month,Day,Weekday,Age_Group
9,60.0,500000.0,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.0,1,525000.0,2020,1,1,Wednesday,Senior

In [ ]:
outliers

print("Number of Outliers:", len(outliers))

Number of Outliers: 1

🔹 Problem 8 : Feature Interaction

In [ ]:
df["Experience_Salary"] = df["Experience"] * df["Salary"]

df

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Month,Day,Weekday,Age_Group,Experience_Salary
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5,-0.538959,0.000000,1,35000.000000,2023,1,15,Sunday,Young,3.000000e+04
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2,-0.391074,0.342105,0,57000.000000,2022,5,10,Tuesday,Adult,2.500000e+05
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8,-0.428045,0.450658,0,51500.000000,2021,8,25,Wednesday,Adult,1.800000e+05
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7,0.000000,0.605263,1,110888.888889,2023,3,18,Saturday,Adult,8.231111e+05
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9,0.126524,0.789474,1,135000.000000,2020,12,5,Saturday,Senior,1.800000e+06
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9,-0.479805,0.157895,0,44000.000000,2022,11,20,Sunday,Adult,1.140000e+05
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1,-0.450228,0.236842,1,49500.000000,2021,7,9,Friday,Adult,2.520000e+05
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0,-0.420651,0.450658,0,52800.000000,2023,6,30,Friday,Adult,2.300000e+05
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3,-0.354103,0.473684,1,62200.000000,2022,9,14,Wednesday,Adult,3.850000e+05
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.000000,1,525000.000000,2020,1,1,Wednesday,Senior,1.250000e+07

Importance of Feature Interaction

- Experience_Salary combines two important features.
- It captures the relationship between salary and work experience.
- It helps the model understand whether experienced employees generally earn higher salaries.
- Such interaction features can improve prediction accuracy because they provide additional information beyond individual features.

🔹 Problem 9 : Feature Selection

In [ ]:
numeric_df = df.select_dtypes(include=np.number)

numeric_df

,Age,Salary,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Month,Day,Experience_Salary
0,22.000,30000.000000,5000,1,4.5,-0.538959,0.000000,1,35000.000000,2023,1,15,3.000000e+04
1,35.000,50000.000000,7000,5,4.2,-0.391074,0.342105,0,57000.000000,2022,5,10,2.500000e+05
2,39.125,45000.000000,6500,4,3.8,-0.428045,0.450658,0,51500.000000,2021,8,25,1.800000e+05
3,45.000,102888.888889,8000,8,4.7,0.000000,0.605263,1,110888.888889,2023,3,18,8.231111e+05
4,52.000,120000.000000,15000,15,4.9,0.126524,0.789474,1,135000.000000,2020,12,5,1.800000e+06
5,28.000,38000.000000,6000,3,3.9,-0.479805,0.157895,0,44000.000000,2022,11,20,1.140000e+05
6,31.000,42000.000000,7500,6,4.1,-0.450228,0.236842,1,49500.000000,2021,7,9,2.520000e+05
7,39.125,46000.000000,6800,5,4.0,-0.420651,0.450658,0,52800.000000,2023,6,30,2.300000e+05
8,40.000,55000.000000,7200,7,4.3,-0.354103,0.473684,1,62200.000000,2022,9,14,3.850000e+05
9,60.000,500000.000000,25000,25,5.0,2.936341,1.000000,1,525000.000000,2020,1,1,1.250000e+07

In [ ]:
#Correlation Matrix
corr_matrix = numeric_df.corr()

corr_matrix

,Age,Salary,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Month,Day,Experience_Salary
Age,1.000000,0.773314,0.850002,0.905412,0.653927,0.773314,1.000000,0.291950,0.777859,-0.602157,-0.041298,-0.432791,0.731164
Salary,0.773314,1.000000,0.954803,0.928935,0.674595,1.000000,0.773314,0.351007,0.999925,-0.564279,-0.426119,-0.595023,0.996063
Purchase_Amount,0.850002,0.954803,1.000000,0.987172,0.737980,0.954803,0.850002,0.397348,0.958374,-0.720382,-0.221567,-0.688062,0.946059
Experience,0.905412,0.928935,0.987172,1.000000,0.761085,0.928935,0.905412,0.443820,0.932997,-0.708058,-0.173649,-0.686865,0.909972
Rating,0.653927,0.674595,0.737980,0.761085,1.000000,0.674595,0.653927,0.748807,0.678415,-0.338058,-0.365023,-0.720915,0.635161
Salary_Standardized,0.773314,1.000000,0.954803,0.928935,0.674595,1.000000,0.773314,0.351007,0.999925,-0.564279,-0.426119,-0.595023,0.996063
Age_Normalized,1.000000,0.773314,0.850002,0.905412,0.653927,0.773314,1.000000,0.291950,0.777859,-0.602157,-0.041298,-0.432791,0.731164
Gender_Label,0.291950,0.351007,0.397348,0.443820,0.748807,0.351007,0.291950,1.000000,0.353545,-0.222681,-0.267560,-0.631988,0.327399
Total_Spending,0.777859,0.999925,0.958374,0.932997,0.678415,0.999925,0.777859,0.353545,1.000000,-0.571724,-0.418447,-0.599923,0.995783
Year,-0.602157,-0.564279,-0.720382,-0.708058,-0.338058,-0.564279,-0.602157,-0.222681,-0.571724,1.000000,-0.300385,0.656390,-0.572605
Month,-0.041298,-0.426119,-0.221567,-0.173649,-0.365023,-0.426119,-0.041298,-0.267560,-0.418447,-0.300385,1.000000,0.138438,-0.428152
Day,-0.432791,-0.595023,-0.688062,-0.686865,-0.720915,-0.595023,-0.432791,-0.631988,-0.599923,0.656390,0.138438,1.000000,-0.592385
Experience_Salary,0.731164,0.996063,0.946059,0.909972,0.635161,0.996063,0.731164,0.327399,0.995783,-0.572605,-0.428152,-0.592385,1.000000

In [ ]:
#Correlation with Purchase Amount
corr_purchase = corr_matrix["Purchase_Amount"]

print(corr_purchase)

Age                    0.850002
Salary                 0.954803
Purchase_Amount        1.000000
Experience             0.987172
Rating                 0.737980
Salary_Standardized    0.954803
Age_Normalized         0.850002
Gender_Label           0.397348
Total_Spending         0.958374
Year                  -0.720382
Month                 -0.221567
Day                   -0.688062
Experience_Salary      0.946059
Name: Purchase_Amount, dtype: float64

In [ ]:
print("Correlation with Purchase_Amount")
print(corr_purchase.sort_values(ascending=False))

Correlation with Purchase_Amount
Purchase_Amount        1.000000
Experience             0.987172
Total_Spending         0.958374
Salary_Standardized    0.954803
Salary                 0.954803
Experience_Salary      0.946059
Age_Normalized         0.850002
Age                    0.850002
Rating                 0.737980
Gender_Label           0.397348
Month                 -0.221567
Day                   -0.688062
Year                  -0.720382
Name: Purchase_Amount, dtype: float64

In [ ]:
#Drop Least Important Feature
least_feature = corr_purchase.drop("Purchase_Amount").abs().idxmin()

print("Least Important Feature :",least_feature)

Least Important Feature : Month

In [ ]:
df_selected = df.drop(columns=[least_feature])

df_selected

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Day,Weekday,Age_Group,Experience_Salary
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5,-0.538959,0.000000,1,35000.000000,2023,15,Sunday,Young,3.000000e+04
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2,-0.391074,0.342105,0,57000.000000,2022,10,Tuesday,Adult,2.500000e+05
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8,-0.428045,0.450658,0,51500.000000,2021,25,Wednesday,Adult,1.800000e+05
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7,0.000000,0.605263,1,110888.888889,2023,18,Saturday,Adult,8.231111e+05
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9,0.126524,0.789474,1,135000.000000,2020,5,Saturday,Senior,1.800000e+06
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9,-0.479805,0.157895,0,44000.000000,2022,20,Sunday,Adult,1.140000e+05
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1,-0.450228,0.236842,1,49500.000000,2021,9,Friday,Adult,2.520000e+05
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0,-0.420651,0.450658,0,52800.000000,2023,30,Friday,Adult,2.300000e+05
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3,-0.354103,0.473684,1,62200.000000,2022,14,Wednesday,Adult,3.850000e+05
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.000000,1,525000.000000,2020,1,Wednesday,Senior,1.250000e+07

In [ ]:
print("Final Dataset after Feature Selection")
df_selected

Final Dataset after Feature Selection

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Day,Weekday,Age_Group,Experience_Salary
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5,-0.538959,0.000000,1,35000.000000,2023,15,Sunday,Young,3.000000e+04
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2,-0.391074,0.342105,0,57000.000000,2022,10,Tuesday,Adult,2.500000e+05
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8,-0.428045,0.450658,0,51500.000000,2021,25,Wednesday,Adult,1.800000e+05
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7,0.000000,0.605263,1,110888.888889,2023,18,Saturday,Adult,8.231111e+05
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9,0.126524,0.789474,1,135000.000000,2020,5,Saturday,Senior,1.800000e+06
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9,-0.479805,0.157895,0,44000.000000,2022,20,Sunday,Adult,1.140000e+05
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1,-0.450228,0.236842,1,49500.000000,2021,9,Friday,Adult,2.520000e+05
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0,-0.420651,0.450658,0,52800.000000,2023,30,Friday,Adult,2.300000e+05
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3,-0.354103,0.473684,1,62200.000000,2022,14,Wednesday,Adult,3.850000e+05
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.000000,1,525000.000000,2020,1,Wednesday,Senior,1.250000e+07

✅ Final Dataset

In [ ]:
print(df_selected.info())

df_selected

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  10 non-null     float64
 1   Salary               10 non-null     float64
 2   Gender               10 non-null     object
 3   City                 10 non-null     object
 4   Date                 10 non-null     datetime64[ns]
 5   Purchase_Amount      10 non-null     int64
 6   Experience           10 non-null     int64
 7   Rating               10 non-null     float64
 8   Salary_Standardized  10 non-null     float64
 9   Age_Normalized       10 non-null     float64
 10  Gender_Label         10 non-null     int64
 11  Total_Spending       10 non-null     float64
 12  Year                 10 non-null     int32
 13  Day                  10 non-null     int32
 14  Weekday              10 non-null     object
 15  Age_Group            10 non-null     category
 16  Experience_Salary    10 non-null     float64
dtypes: category(1), datetime64[ns](1), float64(7), int32(2), int64(3), object(3)
memory usage: 1.4+ KB
None

,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Salary_Standardized,Age_Normalized,Gender_Label,Total_Spending,Year,Day,Weekday,Age_Group,Experience_Salary
0,22.000,30000.000000,Male,Hyderabad,2023-01-15,5000,1,4.5,-0.538959,0.000000,1,35000.000000,2023,15,Sunday,Young,3.000000e+04
1,35.000,50000.000000,Female,Delhi,2022-05-10,7000,5,4.2,-0.391074,0.342105,0,57000.000000,2022,10,Tuesday,Adult,2.500000e+05
2,39.125,45000.000000,Female,Mumbai,2021-08-25,6500,4,3.8,-0.428045,0.450658,0,51500.000000,2021,25,Wednesday,Adult,1.800000e+05
3,45.000,102888.888889,Male,Pune,2023-03-18,8000,8,4.7,0.000000,0.605263,1,110888.888889,2023,18,Saturday,Adult,8.231111e+05
4,52.000,120000.000000,Male,Delhi,2020-12-05,15000,15,4.9,0.126524,0.789474,1,135000.000000,2020,5,Saturday,Senior,1.800000e+06
5,28.000,38000.000000,Female,Hyderabad,2022-11-20,6000,3,3.9,-0.479805,0.157895,0,44000.000000,2022,20,Sunday,Adult,1.140000e+05
6,31.000,42000.000000,Male,Delhi,2021-07-09,7500,6,4.1,-0.450228,0.236842,1,49500.000000,2021,9,Friday,Adult,2.520000e+05
7,39.125,46000.000000,Female,Mumbai,2023-06-30,6800,5,4.0,-0.420651,0.450658,0,52800.000000,2023,30,Friday,Adult,2.300000e+05
8,40.000,55000.000000,Male,Pune,2022-09-14,7200,7,4.3,-0.354103,0.473684,1,62200.000000,2022,14,Wednesday,Adult,3.850000e+05
9,60.000,500000.000000,Male,Delhi,2020-01-01,25000,25,5.0,2.936341,1.000000,1,525000.000000,2020,1,Wednesday,Senior,1.250000e+07

In [ ]:
df_selected.to_csv("feature_engineering_assignment.csv",
                   index=False)